;File automatically generated by CrappyCppHeaderParser.ahk (Copyright@ peixoto)

Global D3D10 := {}
D3D10.IID_ID3D10DeviceChild := "{9B7E4C00-342C-4106-A19F-4F2704F689F0}"
D3D10.IID_ID3D10DepthStencilState := "{2B4B1CC8-A4AD-41f8-8322-CA86FC3EC675}"
D3D10.IID_ID3D10BlendState := "{EDAD8D19-8A35-4d6d-8566-2EA276CDE161}"
D3D10.IID_ID3D10RasterizerState := "{A2A07292-89AF-4345-BE2E-C53D9FBB6E9F}"
D3D10.IID_ID3D10Resource := "{9B7E4C01-342C-4106-A19F-4F2704F689F0}"
D3D10.IID_ID3D10Buffer := "{9B7E4C02-342C-4106-A19F-4F2704F689F0}"
D3D10.IID_ID3D10Texture1D := "{9B7E4C03-342C-4106-A19F-4F2704F689F0}"
D3D10.IID_ID3D10Texture2D := "{9B7E4C04-342C-4106-A19F-4F2704F689F0}"
D3D10.IID_ID3D10Texture3D := "{9B7E4C05-342C-4106-A19F-4F2704F689F0}"
D3D10.IID_ID3D10View := "{C902B03F-60A7-49BA-9936-2A3AB37A7E33}"
D3D10.IID_ID3D10ShaderResourceView := "{9B7E4C07-342C-4106-A19F-4F2704F689F0}"
D3D10.IID_ID3D10RenderTargetView := "{9B7E4C08-342C-4106-A19F-4F2704F689F0}"
D3D10.IID_ID3D10DepthStencilView := "{9B7E4C09-342C-4106-A19F-4F2704F689F0}"
D3D10.IID_ID3D10VertexShader := "{9B7E4C0A-342C-4106-A19F-4F2704F689F0}"
D3D10.IID_ID3D10GeometryShader := "{6316BE88-54CD-4040-AB44-20461BC81F68}"
D3D10.IID_ID3D10PixelShader := "{4968B601-9D00-4cde-8346-8E7F675819B6}"
D3D10.IID_ID3D10InputLayout := "{9B7E4C0B-342C-4106-A19F-4F2704F689F0}"
D3D10.IID_ID3D10SamplerState := "{9B7E4C0C-342C-4106-A19F-4F2704F689F0}"
D3D10.IID_ID3D10Asynchronous := "{9B7E4C0D-342C-4106-A19F-4F2704F689F0}"
D3D10.IID_ID3D10Query := "{9B7E4C0E-342C-4106-A19F-4F2704F689F0}"
D3D10.IID_ID3D10Predicate := "{9B7E4C10-342C-4106-A19F-4F2704F689F0}"
D3D10.IID_ID3D10Counter := "{9B7E4C11-342C-4106-A19F-4F2704F689F0}"
D3D10.IID_ID3D10Device := "{9B7E4C0F-342C-4106-A19F-4F2704F689F0}"
D3D10.IID_ID3D10Multithread := "{9B7E4E00-342C-4106-A19F-4F2704F689F0}"

D3D10.ID3D10Asynchronous:= {}
D3D10.ID3D10Asynchronous.name := "ID3D10Asynchronous"
D3D10.ID3D10Asynchronous.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(Begin)(This)
STDMETHOD(End)(This)
STDMETHOD(GetData)(This,pData,DataSize,GetDataFlags)
STDMETHOD(GetDataSize)(This)
"
)

D3D10.ID3D10BlendState:= {}
D3D10.ID3D10BlendState.name := "ID3D10BlendState"
D3D10.ID3D10BlendState.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetDesc)(This,pDesc)
"
)

D3D10.ID3D10Buffer:= {}
D3D10.ID3D10Buffer.name := "ID3D10Buffer"
D3D10.ID3D10Buffer.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetType)(This,rType)
STDMETHOD(SetEvictionPriority)(This,EvictionPriority)
STDMETHOD(GetEvictionPriority)(This)
STDMETHOD(Map)(This,MapType,MapFlags,ppData)
STDMETHOD(Unmap)(This)
STDMETHOD(GetDesc)(This,pDesc)
"
)

D3D10.ID3D10Counter:= {}
D3D10.ID3D10Counter.name := "ID3D10Counter"
D3D10.ID3D10Counter.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(Begin)(This)
STDMETHOD(End)(This)
STDMETHOD(GetData)(This,pData,DataSize,GetDataFlags)
STDMETHOD(GetDataSize)(This)
STDMETHOD(GetDesc)(This,pDesc)
"
)

D3D10.ID3D10DepthStencilState:= {}
D3D10.ID3D10DepthStencilState.name := "ID3D10DepthStencilState"
D3D10.ID3D10DepthStencilState.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetDesc)(This,pDesc)
"
)

D3D10.ID3D10DepthStencilView:= {}
D3D10.ID3D10DepthStencilView.name := "ID3D10DepthStencilView"
D3D10.ID3D10DepthStencilView.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetResource)(This,ppResource)
STDMETHOD(GetDesc)(This,pDesc)
"
)

D3D10.ID3D10Device:= {}
D3D10.ID3D10Device.name := "ID3D10Device"
D3D10.ID3D10Device.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(VSSetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)
STDMETHOD(PSSetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)
STDMETHOD(PSSetShader)(This,pPixelShader)
STDMETHOD(PSSetSamplers)(This,StartSlot,NumSamplers,ppSamplers)
STDMETHOD(VSSetShader)(This,pVertexShader)
STDMETHOD(DrawIndexed)(This,IndexCount,StartIndexLocation,BaseVertexLocation)
STDMETHOD(Draw)(This,VertexCount,StartVertexLocation)
STDMETHOD(PSSetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)
STDMETHOD(IASetInputLayout)(This,pInputLayout)
STDMETHOD(IASetVertexBuffers)(This,StartSlot,NumBuffers,ppVertexBuffers,pStrides,pOffsets)
STDMETHOD(IASetIndexBuffer)(This,pIndexBuffer,Format,Offset)
STDMETHOD(DrawIndexedInstanced)(This,IndexCountPerInstance,InstanceCount,StartIndexLocation,BaseVertexLocation,StartInstanceLocation)
STDMETHOD(DrawInstanced)(This,VertexCountPerInstance,InstanceCount,StartVertexLocation,StartInstanceLocation)
STDMETHOD(GSSetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)
STDMETHOD(GSSetShader)(This,pShader)
STDMETHOD(IASetPrimitiveTopology)(This,Topology)
STDMETHOD(VSSetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)
STDMETHOD(VSSetSamplers)(This,StartSlot,NumSamplers,ppSamplers)
STDMETHOD(SetPredication)(This,pPredicate,PredicateValue)
STDMETHOD(GSSetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)
STDMETHOD(GSSetSamplers)(This,StartSlot,NumSamplers,ppSamplers)
STDMETHOD(OMSetRenderTargets)(This,NumViews,ppRenderTargetViews,pDepthStencilView)
STDMETHOD(OMSetBlendState)(This,pBlendState,BlendFactor,SampleMask)
STDMETHOD(OMSetDepthStencilState)(This,pDepthStencilState,StencilRef)
STDMETHOD(SOSetTargets)(This,NumBuffers,ppSOTargets,pOffsets)
STDMETHOD(DrawAuto)(This)
STDMETHOD(RSSetState)(This,pRasterizerState)
STDMETHOD(RSSetViewports)(This,NumViewports,pViewports)
STDMETHOD(RSSetScissorRects)(This,NumRects,pRects)
STDMETHOD(CopySubresourceRegion)(This,pDstResource,DstSubresource,DstX,DstY,DstZ,pSrcResource,SrcSubresource,pSrcBox)
STDMETHOD(CopyResource)(This,pDstResource,pSrcResource)
STDMETHOD(UpdateSubresource)(This,pDstResource,DstSubresource,pDstBox,pSrcData,SrcRowPitch,SrcDepthPitch)
STDMETHOD(ClearRenderTargetView)(This,pRenderTargetView,ColorRGBA)
STDMETHOD(ClearDepthStencilView)(This,pDepthStencilView,ClearFlags,Depth,Stencil)
STDMETHOD(GenerateMips)(This,pShaderResourceView)
STDMETHOD(ResolveSubresource)(This,pDstResource,DstSubresource,pSrcResource,SrcSubresource,Format)
STDMETHOD(VSGetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)
STDMETHOD(PSGetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)
STDMETHOD(PSGetShader)(This,ppPixelShader)
STDMETHOD(PSGetSamplers)(This,StartSlot,NumSamplers,ppSamplers)
STDMETHOD(VSGetShader)(This,ppVertexShader)
STDMETHOD(PSGetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)
STDMETHOD(IAGetInputLayout)(This,ppInputLayout)
STDMETHOD(IAGetVertexBuffers)(This,StartSlot,NumBuffers,ppVertexBuffers,pStrides,pOffsets)
STDMETHOD(IAGetIndexBuffer)(This,pIndexBuffer,Format,Offset)
STDMETHOD(GSGetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)
STDMETHOD(GSGetShader)(This,ppGeometryShader)
STDMETHOD(IAGetPrimitiveTopology)(This,pTopology)
STDMETHOD(VSGetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)
STDMETHOD(VSGetSamplers)(This,StartSlot,NumSamplers,ppSamplers)
STDMETHOD(GetPredication)(This,ppPredicate,pPredicateValue)
STDMETHOD(GSGetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)
STDMETHOD(GSGetSamplers)(This,StartSlot,NumSamplers,ppSamplers)
STDMETHOD(OMGetRenderTargets)(This,NumViews,ppRenderTargetViews,ppDepthStencilView)
STDMETHOD(OMGetBlendState)(This,ppBlendState,BlendFactor,pSampleMask)
STDMETHOD(OMGetDepthStencilState)(This,ppDepthStencilState,pStencilRef)
STDMETHOD(SOGetTargets)(This,NumBuffers,ppSOTargets,pOffsets)
STDMETHOD(RSGetState)(This,ppRasterizerState)
STDMETHOD(RSGetViewports)(This,NumViewports,pViewports)
STDMETHOD(RSGetScissorRects)(This,NumRects,pRects)
STDMETHOD(GetDeviceRemovedReason)(This)
STDMETHOD(SetExceptionMode)(This,RaiseFlags)
STDMETHOD(GetExceptionMode)(This)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(ClearState)(This)
STDMETHOD(Flush)(This)
STDMETHOD(CreateBuffer)(This,pDesc,pInitialData,ppBuffer)
STDMETHOD(CreateTexture1D)(This,pDesc,pInitialData,ppTexture1D)
STDMETHOD(CreateTexture2D)(This,pDesc,pInitialData,ppTexture2D)
STDMETHOD(CreateTexture3D)(This,pDesc,pInitialData,ppTexture3D)
STDMETHOD(CreateShaderResourceView)(This,pResource,pDesc,ppSRView)
STDMETHOD(CreateRenderTargetView)(This,pResource,pDesc,ppRTView)
STDMETHOD(CreateDepthStencilView)(This,pResource,pDesc,ppDepthStencilView)
STDMETHOD(CreateInputLayout)(This,pInputElementDescs,NumElements,pShaderBytecodeWithInputSignature,BytecodeLength,ppInputLayout)
STDMETHOD(CreateVertexShader)(This,pShaderBytecode,BytecodeLength,ppVertexShader)
STDMETHOD(CreateGeometryShader)(This,pShaderBytecode,BytecodeLength,ppGeometryShader)
STDMETHOD(CreateGeometryShaderWithStreamOutput)(This,pShaderBytecode,BytecodeLength,pSODeclaration,NumEntries,OutputStreamStride,ppGeometryShader)
STDMETHOD(CreatePixelShader)(This,pShaderBytecode,BytecodeLength,ppPixelShader)
STDMETHOD(CreateBlendState)(This,pBlendStateDesc,ppBlendState)
STDMETHOD(CreateDepthStencilState)(This,pDepthStencilDesc,ppDepthStencilState)
STDMETHOD(CreateRasterizerState)(This,pRasterizerDesc,ppRasterizerState)
STDMETHOD(CreateSamplerState)(This,pSamplerDesc,ppSamplerState)
STDMETHOD(CreateQuery)(This,pQueryDesc,ppQuery)
STDMETHOD(CreatePredicate)(This,pPredicateDesc,ppPredicate)
STDMETHOD(CreateCounter)(This,pCounterDesc,ppCounter)
STDMETHOD(CheckFormatSupport)(This,Format,pFormatSupport)
STDMETHOD(CheckMultisampleQualityLevels)(This,Format,SampleCount,pNumQualityLevels)
STDMETHOD(CheckCounterInfo)(This,pCounterInfo)
STDMETHOD(CheckCounter)(This,pDesc,pType,pActiveCounters,szName,pNameLength,szUnits,pUnitsLength,szDescription,pDescriptionLength)
STDMETHOD(GetCreationFlags)(This)
STDMETHOD(OpenSharedResource)(This,hResource,ReturnedInterface,ppResource)
STDMETHOD(SetTextFilterSize)(This,Width,Height)
STDMETHOD(GetTextFilterSize)(This,pWidth,pHeight)
"
)

D3D10.ID3D10DeviceChild:= {}
D3D10.ID3D10DeviceChild.name := "ID3D10DeviceChild"
D3D10.ID3D10DeviceChild.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
"
)

D3D10.ID3D10GeometryShader:= {}
D3D10.ID3D10GeometryShader.name := "ID3D10GeometryShader"
D3D10.ID3D10GeometryShader.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
"
)

D3D10.ID3D10InputLayout:= {}
D3D10.ID3D10InputLayout.name := "ID3D10InputLayout"
D3D10.ID3D10InputLayout.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
"
)

D3D10.ID3D10Multithread:= {}
D3D10.ID3D10Multithread.name := "ID3D10Multithread"
D3D10.ID3D10Multithread.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(Enter)(This)
STDMETHOD(Leave)(This)
STDMETHOD(SetMultithreadProtected)(This,bMTProtect)
STDMETHOD(GetMultithreadProtected)(This)
"
)

D3D10.ID3D10PixelShader:= {}
D3D10.ID3D10PixelShader.name := "ID3D10PixelShader"
D3D10.ID3D10PixelShader.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
"
)

D3D10.ID3D10Predicate:= {}
D3D10.ID3D10Predicate.name := "ID3D10Predicate"
D3D10.ID3D10Predicate.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(Begin)(This)
STDMETHOD(End)(This)
STDMETHOD(GetData)(This,pData,DataSize,GetDataFlags)
STDMETHOD(GetDataSize)(This)
STDMETHOD(GetDesc)(This,pDesc)
"
)

D3D10.ID3D10Query:= {}
D3D10.ID3D10Query.name := "ID3D10Query"
D3D10.ID3D10Query.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(Begin)(This)
STDMETHOD(End)(This)
STDMETHOD(GetData)(This,pData,DataSize,GetDataFlags)
STDMETHOD(GetDataSize)(This)
STDMETHOD(GetDesc)(This,pDesc)
"
)

D3D10.ID3D10RasterizerState:= {}
D3D10.ID3D10RasterizerState.name := "ID3D10RasterizerState"
D3D10.ID3D10RasterizerState.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetDesc)(This,pDesc)
"
)

D3D10.ID3D10RenderTargetView:= {}
D3D10.ID3D10RenderTargetView.name := "ID3D10RenderTargetView"
D3D10.ID3D10RenderTargetView.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetResource)(This,ppResource)
STDMETHOD(GetDesc)(This,pDesc)
"
)

D3D10.ID3D10Resource:= {}
D3D10.ID3D10Resource.name := "ID3D10Resource"
D3D10.ID3D10Resource.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetType)(This,rType)
STDMETHOD(SetEvictionPriority)(This,EvictionPriority)
STDMETHOD(GetEvictionPriority)(This)
"
)

D3D10.ID3D10SamplerState:= {}
D3D10.ID3D10SamplerState.name := "ID3D10SamplerState"
D3D10.ID3D10SamplerState.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetDesc)(This,pDesc)
"
)

D3D10.ID3D10ShaderResourceView:= {}
D3D10.ID3D10ShaderResourceView.name := "ID3D10ShaderResourceView"
D3D10.ID3D10ShaderResourceView.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetResource)(This,ppResource)
STDMETHOD(GetDesc)(This,pDesc)
"
)

D3D10.ID3D10Texture1D:= {}
D3D10.ID3D10Texture1D.name := "ID3D10Texture1D"
D3D10.ID3D10Texture1D.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetType)(This,rType)
STDMETHOD(SetEvictionPriority)(This,EvictionPriority)
STDMETHOD(GetEvictionPriority)(This)
STDMETHOD(Map)(This,Subresource,MapType,MapFlags,ppData)
STDMETHOD(Unmap)(This,Subresource)
STDMETHOD(GetDesc)(This,pDesc)
"
)

D3D10.ID3D10Texture2D:= {}
D3D10.ID3D10Texture2D.name := "ID3D10Texture2D"
D3D10.ID3D10Texture2D.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetType)(This,rType)
STDMETHOD(SetEvictionPriority)(This,EvictionPriority)
STDMETHOD(GetEvictionPriority)(This)
STDMETHOD(Map)(This,Subresource,MapType,MapFlags,pMappedTex2D)
STDMETHOD(Unmap)(This,Subresource)
STDMETHOD(GetDesc)(This,pDesc)
"
)

D3D10.ID3D10Texture3D:= {}
D3D10.ID3D10Texture3D.name := "ID3D10Texture3D"
D3D10.ID3D10Texture3D.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetType)(This,rType)
STDMETHOD(SetEvictionPriority)(This,EvictionPriority)
STDMETHOD(GetEvictionPriority)(This)
STDMETHOD(Map)(This,Subresource,MapType,MapFlags,pMappedTex3D)
STDMETHOD(Unmap)(This,Subresource)
STDMETHOD(GetDesc)(This,pDesc)
"
)

D3D10.ID3D10VertexShader:= {}
D3D10.ID3D10VertexShader.name := "ID3D10VertexShader"
D3D10.ID3D10VertexShader.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
"
)

D3D10.ID3D10View:= {}
D3D10.ID3D10View.name := "ID3D10View"
D3D10.ID3D10View.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetDevice)(This,ppDevice)
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)
STDMETHOD(GetResource)(This,ppResource)
"
)



Global _FACD3D10 := 2169
Global D3D10_16BIT_INDEX_STRIP_CUT_VALUE := 65535
Global D3D10_32BIT_INDEX_STRIP_CUT_VALUE := 4294967295
Global D3D10_8BIT_INDEX_STRIP_CUT_VALUE := 255
Global D3D10_ANISOTROPIC_FILTERING_BIT := 64
Global D3D10_APPEND_ALIGNED_ELEMENT := 4294967295
Global D3D10_ARRAY_AXIS_ADDRESS_RANGE_BIT_COUNT := 9
Global D3D10_CLIP_OR_CULL_DISTANCE_COUNT := 8
Global D3D10_CLIP_OR_CULL_DISTANCE_ELEMENT_COUNT := 2
Global D3D10_COMMONSHADER_CONSTANT_BUFFER_API_SLOT_COUNT := 14
Global D3D10_COMMONSHADER_CONSTANT_BUFFER_COMPONENT_BIT_COUNT := 32
Global D3D10_COMMONSHADER_CONSTANT_BUFFER_COMPONENTS := 4
Global D3D10_COMMONSHADER_CONSTANT_BUFFER_HW_SLOT_COUNT := 15
Global D3D10_COMMONSHADER_CONSTANT_BUFFER_REGISTER_COMPONENTS := 4
Global D3D10_COMMONSHADER_CONSTANT_BUFFER_REGISTER_COUNT := 15
Global D3D10_COMMONSHADER_CONSTANT_BUFFER_REGISTER_READ_PORTS := 1
Global D3D10_COMMONSHADER_CONSTANT_BUFFER_REGISTER_READS_PER_INST := 1
Global D3D10_COMMONSHADER_FLOWCONTROL_NESTING_LIMIT := 64
Global D3D10_COMMONSHADER_IMMEDIATE_CONSTANT_BUFFER_REGISTER_COMPONENTS := 4
Global D3D10_COMMONSHADER_IMMEDIATE_CONSTANT_BUFFER_REGISTER_COUNT := 1
Global D3D10_COMMONSHADER_IMMEDIATE_CONSTANT_BUFFER_REGISTER_READ_PORTS := 1
Global D3D10_COMMONSHADER_IMMEDIATE_CONSTANT_BUFFER_REGISTER_READS_PER_INST := 1
Global D3D10_COMMONSHADER_IMMEDIATE_VALUE_COMPONENT_BIT_COUNT := 32
Global D3D10_COMMONSHADER_INPUT_RESOURCE_REGISTER_COMPONENTS := 1
Global D3D10_COMMONSHADER_INPUT_RESOURCE_REGISTER_COUNT := 128
Global D3D10_COMMONSHADER_INPUT_RESOURCE_REGISTER_READ_PORTS := 1
Global D3D10_COMMONSHADER_INPUT_RESOURCE_REGISTER_READS_PER_INST := 1
Global D3D10_COMMONSHADER_INPUT_RESOURCE_SLOT_COUNT := 128
Global D3D10_COMMONSHADER_SAMPLER_REGISTER_COMPONENTS := 1
Global D3D10_COMMONSHADER_SAMPLER_REGISTER_COUNT := 16
Global D3D10_COMMONSHADER_SAMPLER_REGISTER_READ_PORTS := 1
Global D3D10_COMMONSHADER_SAMPLER_REGISTER_READS_PER_INST := 1
Global D3D10_COMMONSHADER_SAMPLER_SLOT_COUNT := 16
Global D3D10_COMMONSHADER_SUBROUTINE_NESTING_LIMIT := 32
Global D3D10_COMMONSHADER_TEMP_REGISTER_COMPONENT_BIT_COUNT := 32
Global D3D10_COMMONSHADER_TEMP_REGISTER_COMPONENTS := 4
Global D3D10_COMMONSHADER_TEMP_REGISTER_COUNT := 4096
Global D3D10_COMMONSHADER_TEMP_REGISTER_READ_PORTS := 3
Global D3D10_COMMONSHADER_TEMP_REGISTER_READS_PER_INST := 3
Global D3D10_COMMONSHADER_TEXCOORD_RANGE_REDUCTION_MAX := 10
Global D3D10_COMMONSHADER_TEXCOORD_RANGE_REDUCTION_MIN := -10
Global D3D10_COMMONSHADER_TEXEL_OFFSET_MAX_NEGATIVE := -8
Global D3D10_COMMONSHADER_TEXEL_OFFSET_MAX_POSITIVE := 7
Global D3D10_COMPARISON_FILTERING_BIT := 128
Global D3D10_DEFAULT_DEPTH_BIAS := 0
Global D3D10_DEFAULT_RENDER_TARGET_ARRAY_INDEX := 0
Global D3D10_DEFAULT_SAMPLE_MASK := 4294967295
Global D3D10_DEFAULT_SCISSOR_ENDX := 0
Global D3D10_DEFAULT_SCISSOR_ENDY := 0
Global D3D10_DEFAULT_SCISSOR_STARTX := 0
Global D3D10_DEFAULT_SCISSOR_STARTY := 0
Global D3D10_DEFAULT_STENCIL_READ_MASK := 255
Global D3D10_DEFAULT_STENCIL_REFERENCE := 0
Global D3D10_DEFAULT_STENCIL_WRITE_MASK := 255
Global D3D10_DEFAULT_VIEWPORT_AND_SCISSORRECT_INDEX := 0
Global D3D10_DEFAULT_VIEWPORT_HEIGHT := 0
Global D3D10_DEFAULT_VIEWPORT_TOPLEFTX := 0
Global D3D10_DEFAULT_VIEWPORT_TOPLEFTY := 0
Global D3D10_DEFAULT_VIEWPORT_WIDTH := 0
Global D3D10_FILTER_TYPE_MASK := 3
Global D3D10_GS_INPUT_PRIM_CONST_REGISTER_COMPONENT_BIT_COUNT := 32
Global D3D10_GS_INPUT_PRIM_CONST_REGISTER_COMPONENTS := 1
Global D3D10_GS_INPUT_PRIM_CONST_REGISTER_COUNT := 1
Global D3D10_GS_INPUT_PRIM_CONST_REGISTER_READ_PORTS := 1
Global D3D10_GS_INPUT_PRIM_CONST_REGISTER_READS_PER_INST := 2
Global D3D10_GS_INPUT_REGISTER_COMPONENT_BIT_COUNT := 32
Global D3D10_GS_INPUT_REGISTER_COMPONENTS := 4
Global D3D10_GS_INPUT_REGISTER_COUNT := 16
Global D3D10_GS_INPUT_REGISTER_READ_PORTS := 1
Global D3D10_GS_INPUT_REGISTER_READS_PER_INST := 2
Global D3D10_GS_INPUT_REGISTER_VERTICES := 6
Global D3D10_GS_OUTPUT_ELEMENTS := 32
Global D3D10_GS_OUTPUT_REGISTER_COMPONENT_BIT_COUNT := 32
Global D3D10_GS_OUTPUT_REGISTER_COMPONENTS := 4
Global D3D10_GS_OUTPUT_REGISTER_COUNT := 32
Global D3D10_IA_DEFAULT_INDEX_BUFFER_OFFSET_IN_BYTES := 0
Global D3D10_IA_DEFAULT_PRIMITIVE_TOPOLOGY := 0
Global D3D10_IA_DEFAULT_VERTEX_BUFFER_OFFSET_IN_BYTES := 0
Global D3D10_IA_INDEX_INPUT_RESOURCE_SLOT_COUNT := 1
Global D3D10_IA_INSTANCE_ID_BIT_COUNT := 32
Global D3D10_IA_INTEGER_ARITHMETIC_BIT_COUNT := 32
Global D3D10_IA_PRIMITIVE_ID_BIT_COUNT := 32
Global D3D10_IA_VERTEX_ID_BIT_COUNT := 32
Global D3D10_IA_VERTEX_INPUT_RESOURCE_SLOT_COUNT := 16
Global D3D10_IA_VERTEX_INPUT_STRUCTURE_ELEMENT_COUNT := 16
Global D3D10_IA_VERTEX_INPUT_STRUCTURE_ELEMENTS_COMPONENTS := 64
Global D3D10_INTEGER_DIVIDE_BY_ZERO_QUOTIENT := 4294967295
Global D3D10_INTEGER_DIVIDE_BY_ZERO_REMAINDER := 4294967295
Global D3D10_MAG_FILTER_SHIFT := 2
Global D3D10_MAX_MAXANISOTROPY := 16
Global D3D10_MAX_MULTISAMPLE_SAMPLE_COUNT := 32
Global D3D10_MAX_TEXTURE_DIMENSION_2_TO_EXP := 17
Global D3D10_MIN_FILTER_SHIFT := 4
Global D3D10_MIN_MAXANISOTROPY := 0
Global D3D10_MIP_FILTER_SHIFT := 0
Global D3D10_MIP_LOD_FRACTIONAL_BIT_COUNT := 6
Global D3D10_MIP_LOD_RANGE_BIT_COUNT := 8
Global D3D10_NONSAMPLE_FETCH_OUT_OF_RANGE_ACCESS_RESULT := 0
Global D3D10_PIXEL_ADDRESS_RANGE_BIT_COUNT := 13
Global D3D10_PRE_SCISSOR_PIXEL_ADDRESS_RANGE_BIT_COUNT := 15
Global D3D10_PS_FRONTFACING_DEFAULT_VALUE := 4294967295
Global D3D10_PS_FRONTFACING_FALSE_VALUE := 0
Global D3D10_PS_FRONTFACING_TRUE_VALUE := 4294967295
Global D3D10_PS_INPUT_REGISTER_COMPONENT_BIT_COUNT := 32
Global D3D10_PS_INPUT_REGISTER_COMPONENTS := 4
Global D3D10_PS_INPUT_REGISTER_COUNT := 32
Global D3D10_PS_INPUT_REGISTER_READ_PORTS := 1
Global D3D10_PS_INPUT_REGISTER_READS_PER_INST := 2
Global D3D10_PS_OUTPUT_DEPTH_REGISTER_COMPONENT_BIT_COUNT := 32
Global D3D10_PS_OUTPUT_DEPTH_REGISTER_COMPONENTS := 1
Global D3D10_PS_OUTPUT_DEPTH_REGISTER_COUNT := 1
Global D3D10_PS_OUTPUT_REGISTER_COMPONENT_BIT_COUNT := 32
Global D3D10_PS_OUTPUT_REGISTER_COMPONENTS := 4
Global D3D10_PS_OUTPUT_REGISTER_COUNT := 8
Global D3D10_REQ_BLEND_OBJECT_COUNT_PER_CONTEXT := 4096
Global D3D10_REQ_BUFFER_RESOURCE_TEXEL_COUNT_2_TO_EXP := 27
Global D3D10_REQ_CONSTANT_BUFFER_ELEMENT_COUNT := 4096
Global D3D10_REQ_DEPTH_STENCIL_OBJECT_COUNT_PER_CONTEXT := 4096
Global D3D10_REQ_DRAW_VERTEX_COUNT_2_TO_EXP := 32
Global D3D10_REQ_DRAWINDEXED_INDEX_COUNT_2_TO_EXP := 32
Global D3D10_REQ_FILTERING_HW_ADDRESSABLE_RESOURCE_DIMENSION := 8192
Global D3D10_REQ_GS_INVOCATION_32BIT_OUTPUT_COMPONENT_LIMIT := 1024
Global D3D10_REQ_IMMEDIATE_CONSTANT_BUFFER_ELEMENT_COUNT := 4096
Global D3D10_REQ_MAXANISOTROPY := 16
Global D3D10_REQ_MIP_LEVELS := 14
Global D3D10_REQ_MULTI_ELEMENT_STRUCTURE_SIZE_IN_BYTES := 2048
Global D3D10_REQ_RASTERIZER_OBJECT_COUNT_PER_CONTEXT := 4096
Global D3D10_REQ_RENDER_TO_BUFFER_WINDOW_WIDTH := 8192
Global D3D10_REQ_RESOURCE_SIZE_IN_MEGABYTES := 128
Global D3D10_REQ_RESOURCE_VIEW_COUNT_PER_CONTEXT_2_TO_EXP := 20
Global D3D10_REQ_SAMPLER_OBJECT_COUNT_PER_CONTEXT := 4096
Global D3D10_REQ_TEXTURE1D_ARRAY_AXIS_DIMENSION := 512
Global D3D10_REQ_TEXTURE1D_U_DIMENSION := 8192
Global D3D10_REQ_TEXTURE2D_ARRAY_AXIS_DIMENSION := 512
Global D3D10_REQ_TEXTURE2D_U_OR_V_DIMENSION := 8192
Global D3D10_REQ_TEXTURE3D_U_V_OR_W_DIMENSION := 2048
Global D3D10_REQ_TEXTURECUBE_DIMENSION := 8192
Global D3D10_RESINFO_INSTRUCTION_MISSING_COMPONENT_RETVAL := 0
Global D3D10_SDK_VERSION := 29
Global D3D10_SHADER_MAJOR_VERSION := 4
Global D3D10_SHADER_MINOR_VERSION := 0
Global D3D10_SHIFT_INSTRUCTION_PAD_VALUE := 0
Global D3D10_SHIFT_INSTRUCTION_SHIFT_VALUE_BIT_COUNT := 5
Global D3D10_SIMULTANEOUS_RENDER_TARGET_COUNT := 8
Global D3D10_SO_BUFFER_MAX_STRIDE_IN_BYTES := 2048
Global D3D10_SO_BUFFER_MAX_WRITE_WINDOW_IN_BYTES := 256
Global D3D10_SO_BUFFER_SLOT_COUNT := 4
Global D3D10_SO_DDI_REGISTER_INDEX_DENOTING_GAP := 4294967295
Global D3D10_SO_MULTIPLE_BUFFER_ELEMENTS_PER_BUFFER := 1
Global D3D10_SO_SINGLE_BUFFER_COMPONENT_LIMIT := 64
Global D3D10_STANDARD_COMPONENT_BIT_COUNT := 32
Global D3D10_STANDARD_COMPONENT_BIT_COUNT_DOUBLED := 64
Global D3D10_STANDARD_MAXIMUM_ELEMENT_ALIGNMENT_BYTE_MULTIPLE := 4
Global D3D10_STANDARD_PIXEL_COMPONENT_COUNT := 128
Global D3D10_STANDARD_PIXEL_ELEMENT_COUNT := 32
Global D3D10_STANDARD_VECTOR_SIZE := 4
Global D3D10_STANDARD_VERTEX_ELEMENT_COUNT := 16
Global D3D10_STANDARD_VERTEX_TOTAL_COMPONENT_COUNT := 64
Global D3D10_SUBPIXEL_FRACTIONAL_BIT_COUNT := 8
Global D3D10_SUBTEXEL_FRACTIONAL_BIT_COUNT := 6
Global D3D10_TEXEL_ADDRESS_RANGE_BIT_COUNT := 18
Global D3D10_TEXT_1BIT_BIT := 2147483648
Global D3D10_UNBOUND_MEMORY_ACCESS_RESULT := 0
Global D3D10_VIEWPORT_AND_SCISSORRECT_MAX_INDEX := 15
Global D3D10_VIEWPORT_AND_SCISSORRECT_OBJECT_COUNT_PER_PIPELINE := 16
Global D3D10_VIEWPORT_BOUNDS_MAX := 16383
Global D3D10_VIEWPORT_BOUNDS_MIN := -16384
Global D3D10_VS_INPUT_REGISTER_COMPONENT_BIT_COUNT := 32
Global D3D10_VS_INPUT_REGISTER_COMPONENTS := 4
Global D3D10_VS_INPUT_REGISTER_COUNT := 16
Global D3D10_VS_INPUT_REGISTER_READ_PORTS := 1
Global D3D10_VS_INPUT_REGISTER_READS_PER_INST := 2
Global D3D10_VS_OUTPUT_REGISTER_COMPONENT_BIT_COUNT := 32
Global D3D10_VS_OUTPUT_REGISTER_COMPONENTS := 4
Global D3D10_VS_OUTPUT_REGISTER_COUNT := 16
Global D3D10_WHQL_CONTEXT_COUNT_FOR_RESOURCE_LIMIT := 10
Global D3D10_WHQL_DRAW_VERTEX_COUNT_2_TO_EXP := 25
Global D3D10_WHQL_DRAWINDEXED_INDEX_COUNT_2_TO_EXP := 25
Global D3D_MAJOR_VERSION := 10
Global D3D_MINOR_VERSION := 0
Global D3D_SPEC_DATE_DAY := 8
Global D3D_SPEC_DATE_MONTH := 8
Global D3D_SPEC_DATE_YEAR := 2006

D3D10.err := {}

