;File automatically generated by CrappyCppHeaderParser.ahk (Copyright@ peixoto)

Global D3D11_4 := {}
D3D11_4.IID_ID3D11Device4 := "{8992ab71-02e6-4b8d-ba48-b056dcda42c4}"
D3D11_4.IID_ID3D11Device5 := "{8ffde202-a0e7-45df-9e01-e837801b5ea0}"
D3D11_4.IID_ID3D11Multithread := "{9B7E4E00-342C-4106-A19F-4F2704F689F0}"
D3D11_4.IID_ID3D11VideoContext2 := "{C4E7374C-6243-4D1B-AE87-52B4F740E261}"

D3D11_4.ID3D11Device4 := {}
D3D11_4.ID3D11Device4.name := "ID3D11Device4"
D3D11_4.ID3D11Device4.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(CreateBuffer)(This,pDesc,pInitialData,ppBuffer)	\
STDMETHOD(CreateTexture1D)(This,pDesc,pInitialData,ppTexture1D)	\
STDMETHOD(CreateTexture2D)(This,pDesc,pInitialData,ppTexture2D)	\
STDMETHOD(CreateTexture3D)(This,pDesc,pInitialData,ppTexture3D)	\
STDMETHOD(CreateShaderResourceView)(This,pResource,pDesc,ppSRView)	\
STDMETHOD(CreateUnorderedAccessView)(This,pResource,pDesc,ppUAView)	\
STDMETHOD(CreateRenderTargetView)(This,pResource,pDesc,ppRTView)	\
STDMETHOD(CreateDepthStencilView)(This,pResource,pDesc,ppDepthStencilView)	\
STDMETHOD(CreateInputLayout)(This,pInputElementDescs,NumElements,pShaderBytecodeWithInputSignature,BytecodeLength,ppInputLayout)	\
STDMETHOD(CreateVertexShader)(This,pShaderBytecode,BytecodeLength,pClassLinkage,ppVertexShader)	\
STDMETHOD(CreateGeometryShader)(This,pShaderBytecode,BytecodeLength,pClassLinkage,ppGeometryShader)	\
STDMETHOD(CreateGeometryShaderWithStreamOutput)(This,pShaderBytecode,BytecodeLength,pSODeclaration,NumEntries,pBufferStrides,NumStrides,RasterizedStream,pClassLinkage,ppGeometryShader)	\
STDMETHOD(CreatePixelShader)(This,pShaderBytecode,BytecodeLength,pClassLinkage,ppPixelShader)	\
STDMETHOD(CreateHullShader)(This,pShaderBytecode,BytecodeLength,pClassLinkage,ppHullShader)	\
STDMETHOD(CreateDomainShader)(This,pShaderBytecode,BytecodeLength,pClassLinkage,ppDomainShader)	\
STDMETHOD(CreateComputeShader)(This,pShaderBytecode,BytecodeLength,pClassLinkage,ppComputeShader)	\
STDMETHOD(CreateClassLinkage)(This,ppLinkage)	\
STDMETHOD(CreateBlendState)(This,pBlendStateDesc,ppBlendState)	\
STDMETHOD(CreateDepthStencilState)(This,pDepthStencilDesc,ppDepthStencilState)	\
STDMETHOD(CreateRasterizerState)(This,pRasterizerDesc,ppRasterizerState)	\
STDMETHOD(CreateSamplerState)(This,pSamplerDesc,ppSamplerState)	\
STDMETHOD(CreateQuery)(This,pQueryDesc,ppQuery)	\
STDMETHOD(CreatePredicate)(This,pPredicateDesc,ppPredicate)	\
STDMETHOD(CreateCounter)(This,pCounterDesc,ppCounter)	\
STDMETHOD(CreateDeferredContext)(This,ContextFlags,ppDeferredContext)	\
STDMETHOD(OpenSharedResource)(This,hResource,ReturnedInterface,ppResource)	\
STDMETHOD(CheckFormatSupport)(This,Format,pFormatSupport)	\
STDMETHOD(CheckMultisampleQualityLevels)(This,Format,SampleCount,pNumQualityLevels)	\
STDMETHOD(CheckCounterInfo)(This,pCounterInfo)	\
STDMETHOD(CheckCounter)(This,pDesc,pType,pActiveCounters,szName,pNameLength,szUnits,pUnitsLength,szDescription,pDescriptionLength)	\
STDMETHOD(CheckFeatureSupport)(This,Feature,pFeatureSupportData,FeatureSupportDataSize)	\
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)	\
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)	\
STDMETHOD(GetFeatureLevel)(This)	\
STDMETHOD(GetCreationFlags)(This)	\
STDMETHOD(GetDeviceRemovedReason)(This)	\
STDMETHOD(GetImmediateContext)(This,ppImmediateContext)	\
STDMETHOD(SetExceptionMode)(This,RaiseFlags)	\
STDMETHOD(GetExceptionMode)(This)	\
STDMETHOD(GetImmediateContext1)(This,ppImmediateContext)	\
STDMETHOD(CreateDeferredContext1)(This,ContextFlags,ppDeferredContext)	\
STDMETHOD(CreateBlendState1)(This,pBlendStateDesc,ppBlendState)	\
STDMETHOD(CreateRasterizerState1)(This,pRasterizerDesc,ppRasterizerState)	\
STDMETHOD(CreateDeviceContextState)(This,Flags,pFeatureLevels,FeatureLevels,SDKVersion,EmulatedInterface,pChosenFeatureLevel,ppContextState)	\
STDMETHOD(OpenSharedResource1)(This,hResource,returnedInterface,ppResource)	\
STDMETHOD(OpenSharedResourceByName)(This,lpName,dwDesiredAccess,returnedInterface,ppResource)	\
STDMETHOD(GetImmediateContext2)(This,ppImmediateContext)	\
STDMETHOD(CreateDeferredContext2)(This,ContextFlags,ppDeferredContext)	\
STDMETHOD(GetResourceTiling)(This,pTiledResource,pNumTilesForEntireResource,pPackedMipDesc,pStandardTileShapeForNonPackedMips,pNumSubresourceTilings,FirstSubresourceTilingToGet,pSubresourceTilingsForNonPackedMips)	\
STDMETHOD(CheckMultisampleQualityLevels1)(This,Format,SampleCount,Flags,pNumQualityLevels)	\
STDMETHOD(CreateTexture2D1)(This,pDesc1,pInitialData,ppTexture2D)	\
STDMETHOD(CreateTexture3D1)(This,pDesc1,pInitialData,ppTexture3D)	\
STDMETHOD(CreateRasterizerState2)(This,pRasterizerDesc,ppRasterizerState)	\
STDMETHOD(CreateShaderResourceView1)(This,pResource,pDesc1,ppSRView1)	\
STDMETHOD(CreateUnorderedAccessView1)(This,pResource,pDesc1,ppUAView1)	\
STDMETHOD(CreateRenderTargetView1)(This,pResource,pDesc1,ppRTView1)	\
STDMETHOD(CreateQuery1)(This,pQueryDesc1,ppQuery1)	\
STDMETHOD(GetImmediateContext3)(This,ppImmediateContext)	\
STDMETHOD(CreateDeferredContext3)(This,ContextFlags,ppDeferredContext)	\
STDMETHOD(WriteToSubresource)(This,pDstResource,DstSubresource,pDstBox,pSrcData,SrcRowPitch,SrcDepthPitch)	\
STDMETHOD(ReadFromSubresource)(This,pDstData,DstRowPitch,DstDepthPitch,pSrcResource,SrcSubresource,pSrcBox)	\
STDMETHOD(RegisterDeviceRemovedEvent)(This,hEvent,pdwCookie)	\
STDMETHOD(UnregisterDeviceRemoved)(This,dwCookie)	\
"
)

D3D11_4.ID3D11Device5 := {}
D3D11_4.ID3D11Device5.name := "ID3D11Device5"
D3D11_4.ID3D11Device5.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(CreateBuffer)(This,pDesc,pInitialData,ppBuffer)	\
STDMETHOD(CreateTexture1D)(This,pDesc,pInitialData,ppTexture1D)	\
STDMETHOD(CreateTexture2D)(This,pDesc,pInitialData,ppTexture2D)	\
STDMETHOD(CreateTexture3D)(This,pDesc,pInitialData,ppTexture3D)	\
STDMETHOD(CreateShaderResourceView)(This,pResource,pDesc,ppSRView)	\
STDMETHOD(CreateUnorderedAccessView)(This,pResource,pDesc,ppUAView)	\
STDMETHOD(CreateRenderTargetView)(This,pResource,pDesc,ppRTView)	\
STDMETHOD(CreateDepthStencilView)(This,pResource,pDesc,ppDepthStencilView)	\
STDMETHOD(CreateInputLayout)(This,pInputElementDescs,NumElements,pShaderBytecodeWithInputSignature,BytecodeLength,ppInputLayout)	\
STDMETHOD(CreateVertexShader)(This,pShaderBytecode,BytecodeLength,pClassLinkage,ppVertexShader)	\
STDMETHOD(CreateGeometryShader)(This,pShaderBytecode,BytecodeLength,pClassLinkage,ppGeometryShader)	\
STDMETHOD(CreateGeometryShaderWithStreamOutput)(This,pShaderBytecode,BytecodeLength,pSODeclaration,NumEntries,pBufferStrides,NumStrides,RasterizedStream,pClassLinkage,ppGeometryShader)	\
STDMETHOD(CreatePixelShader)(This,pShaderBytecode,BytecodeLength,pClassLinkage,ppPixelShader)	\
STDMETHOD(CreateHullShader)(This,pShaderBytecode,BytecodeLength,pClassLinkage,ppHullShader)	\
STDMETHOD(CreateDomainShader)(This,pShaderBytecode,BytecodeLength,pClassLinkage,ppDomainShader)	\
STDMETHOD(CreateComputeShader)(This,pShaderBytecode,BytecodeLength,pClassLinkage,ppComputeShader)	\
STDMETHOD(CreateClassLinkage)(This,ppLinkage)	\
STDMETHOD(CreateBlendState)(This,pBlendStateDesc,ppBlendState)	\
STDMETHOD(CreateDepthStencilState)(This,pDepthStencilDesc,ppDepthStencilState)	\
STDMETHOD(CreateRasterizerState)(This,pRasterizerDesc,ppRasterizerState)	\
STDMETHOD(CreateSamplerState)(This,pSamplerDesc,ppSamplerState)	\
STDMETHOD(CreateQuery)(This,pQueryDesc,ppQuery)	\
STDMETHOD(CreatePredicate)(This,pPredicateDesc,ppPredicate)	\
STDMETHOD(CreateCounter)(This,pCounterDesc,ppCounter)	\
STDMETHOD(CreateDeferredContext)(This,ContextFlags,ppDeferredContext)	\
STDMETHOD(OpenSharedResource)(This,hResource,ReturnedInterface,ppResource)	\
STDMETHOD(CheckFormatSupport)(This,Format,pFormatSupport)	\
STDMETHOD(CheckMultisampleQualityLevels)(This,Format,SampleCount,pNumQualityLevels)	\
STDMETHOD(CheckCounterInfo)(This,pCounterInfo)	\
STDMETHOD(CheckCounter)(This,pDesc,pType,pActiveCounters,szName,pNameLength,szUnits,pUnitsLength,szDescription,pDescriptionLength)	\
STDMETHOD(CheckFeatureSupport)(This,Feature,pFeatureSupportData,FeatureSupportDataSize)	\
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)	\
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)	\
STDMETHOD(GetFeatureLevel)(This)	\
STDMETHOD(GetCreationFlags)(This)	\
STDMETHOD(GetDeviceRemovedReason)(This)	\
STDMETHOD(GetImmediateContext)(This,ppImmediateContext)	\
STDMETHOD(SetExceptionMode)(This,RaiseFlags)	\
STDMETHOD(GetExceptionMode)(This)	\
STDMETHOD(GetImmediateContext1)(This,ppImmediateContext)	\
STDMETHOD(CreateDeferredContext1)(This,ContextFlags,ppDeferredContext)	\
STDMETHOD(CreateBlendState1)(This,pBlendStateDesc,ppBlendState)	\
STDMETHOD(CreateRasterizerState1)(This,pRasterizerDesc,ppRasterizerState)	\
STDMETHOD(CreateDeviceContextState)(This,Flags,pFeatureLevels,FeatureLevels,SDKVersion,EmulatedInterface,pChosenFeatureLevel,ppContextState)	\
STDMETHOD(OpenSharedResource1)(This,hResource,returnedInterface,ppResource)	\
STDMETHOD(OpenSharedResourceByName)(This,lpName,dwDesiredAccess,returnedInterface,ppResource)	\
STDMETHOD(GetImmediateContext2)(This,ppImmediateContext)	\
STDMETHOD(CreateDeferredContext2)(This,ContextFlags,ppDeferredContext)	\
STDMETHOD(GetResourceTiling)(This,pTiledResource,pNumTilesForEntireResource,pPackedMipDesc,pStandardTileShapeForNonPackedMips,pNumSubresourceTilings,FirstSubresourceTilingToGet,pSubresourceTilingsForNonPackedMips)	\
STDMETHOD(CheckMultisampleQualityLevels1)(This,Format,SampleCount,Flags,pNumQualityLevels)	\
STDMETHOD(CreateTexture2D1)(This,pDesc1,pInitialData,ppTexture2D)	\
STDMETHOD(CreateTexture3D1)(This,pDesc1,pInitialData,ppTexture3D)	\
STDMETHOD(CreateRasterizerState2)(This,pRasterizerDesc,ppRasterizerState)	\
STDMETHOD(CreateShaderResourceView1)(This,pResource,pDesc1,ppSRView1)	\
STDMETHOD(CreateUnorderedAccessView1)(This,pResource,pDesc1,ppUAView1)	\
STDMETHOD(CreateRenderTargetView1)(This,pResource,pDesc1,ppRTView1)	\
STDMETHOD(CreateQuery1)(This,pQueryDesc1,ppQuery1)	\
STDMETHOD(GetImmediateContext3)(This,ppImmediateContext)	\
STDMETHOD(CreateDeferredContext3)(This,ContextFlags,ppDeferredContext)	\
STDMETHOD(WriteToSubresource)(This,pDstResource,DstSubresource,pDstBox,pSrcData,SrcRowPitch,SrcDepthPitch)	\
STDMETHOD(ReadFromSubresource)(This,pDstData,DstRowPitch,DstDepthPitch,pSrcResource,SrcSubresource,pSrcBox)	\
STDMETHOD(RegisterDeviceRemovedEvent)(This,hEvent,pdwCookie)	\
STDMETHOD(UnregisterDeviceRemoved)(This,dwCookie)	\
STDMETHOD(OpenSharedFence)(This,hFence,ReturnedInterface,ppFence)	\
STDMETHOD(CreateFence)(This,InitialValue,Flags,ReturnedInterface,ppFence)	\
"
)

D3D11_4.ID3D11Multithread := {}
D3D11_4.ID3D11Multithread.name := "ID3D11Multithread"
D3D11_4.ID3D11Multithread.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(Enter)(This)	\
STDMETHOD(Leave)(This)	\
STDMETHOD(SetMultithreadProtected)(This,bMTProtect)	\
STDMETHOD(GetMultithreadProtected)(This)	\
"
)

D3D11_4.ID3D11VideoContext2 := {}
D3D11_4.ID3D11VideoContext2.name := "ID3D11VideoContext2"
D3D11_4.ID3D11VideoContext2.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(GetDevice)(This,ppDevice)	\
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)	\
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)	\
STDMETHOD(GetDecoderBuffer)(This,pDecoder,Type,pBufferSize,ppBuffer)	\
STDMETHOD(ReleaseDecoderBuffer)(This,pDecoder,Type)	\
STDMETHOD(DecoderBeginFrame)(This,pDecoder,pView,ContentKeySize,pContentKey)	\
STDMETHOD(DecoderEndFrame)(This,pDecoder)	\
STDMETHOD(SubmitDecoderBuffers)(This,pDecoder,NumBuffers,pBufferDesc)	\
STDMETHOD(DecoderExtension)(This,pDecoder,pExtensionData)	\
STDMETHOD(VideoProcessorSetOutputTargetRect)(This,pVideoProcessor,Enable,pRect)	\
STDMETHOD(VideoProcessorSetOutputBackgroundColor)(This,pVideoProcessor,YCbCr,pColor)	\
STDMETHOD(VideoProcessorSetOutputColorSpace)(This,pVideoProcessor,pColorSpace)	\
STDMETHOD(VideoProcessorSetOutputAlphaFillMode)(This,pVideoProcessor,AlphaFillMode,StreamIndex)	\
STDMETHOD(VideoProcessorSetOutputConstriction)(This,pVideoProcessor,Enable,Size)	\
STDMETHOD(VideoProcessorSetOutputStereoMode)(This,pVideoProcessor,Enable)	\
STDMETHOD(VideoProcessorSetOutputExtension)(This,pVideoProcessor,pExtensionGuid,DataSize,pData)	\
STDMETHOD(VideoProcessorGetOutputTargetRect)(This,pVideoProcessor,Enabled,pRect)	\
STDMETHOD(VideoProcessorGetOutputBackgroundColor)(This,pVideoProcessor,pYCbCr,pColor)	\
STDMETHOD(VideoProcessorGetOutputColorSpace)(This,pVideoProcessor,pColorSpace)	\
STDMETHOD(VideoProcessorGetOutputAlphaFillMode)(This,pVideoProcessor,pAlphaFillMode,pStreamIndex)	\
STDMETHOD(VideoProcessorGetOutputConstriction)(This,pVideoProcessor,pEnabled,pSize)	\
STDMETHOD(VideoProcessorGetOutputStereoMode)(This,pVideoProcessor,pEnabled)	\
STDMETHOD(VideoProcessorGetOutputExtension)(This,pVideoProcessor,pExtensionGuid,DataSize,pData)	\
STDMETHOD(VideoProcessorSetStreamFrameFormat)(This,pVideoProcessor,StreamIndex,FrameFormat)	\
STDMETHOD(VideoProcessorSetStreamColorSpace)(This,pVideoProcessor,StreamIndex,pColorSpace)	\
STDMETHOD(VideoProcessorSetStreamOutputRate)(This,pVideoProcessor,StreamIndex,OutputRate,RepeatFrame,pCustomRate)	\
STDMETHOD(VideoProcessorSetStreamSourceRect)(This,pVideoProcessor,StreamIndex,Enable,pRect)	\
STDMETHOD(VideoProcessorSetStreamDestRect)(This,pVideoProcessor,StreamIndex,Enable,pRect)	\
STDMETHOD(VideoProcessorSetStreamAlpha)(This,pVideoProcessor,StreamIndex,Enable,Alpha)	\
STDMETHOD(VideoProcessorSetStreamPalette)(This,pVideoProcessor,StreamIndex,Count,pEntries)	\
STDMETHOD(VideoProcessorSetStreamPixelAspectRatio)(This,pVideoProcessor,StreamIndex,Enable,pSourceAspectRatio,pDestinationAspectRatio)	\
STDMETHOD(VideoProcessorSetStreamLumaKey)(This,pVideoProcessor,StreamIndex,Enable,Lower,Upper)	\
STDMETHOD(VideoProcessorSetStreamStereoFormat)(This,pVideoProcessor,StreamIndex,Enable,Format,LeftViewFrame0,BaseViewFrame0,FlipMode,MonoOffset)	\
STDMETHOD(VideoProcessorSetStreamAutoProcessingMode)(This,pVideoProcessor,StreamIndex,Enable)	\
STDMETHOD(VideoProcessorSetStreamFilter)(This,pVideoProcessor,StreamIndex,Filter,Enable,Level)	\
STDMETHOD(VideoProcessorSetStreamExtension)(This,pVideoProcessor,StreamIndex,pExtensionGuid,DataSize,pData)	\
STDMETHOD(VideoProcessorGetStreamFrameFormat)(This,pVideoProcessor,StreamIndex,pFrameFormat)	\
STDMETHOD(VideoProcessorGetStreamColorSpace)(This,pVideoProcessor,StreamIndex,pColorSpace)	\
STDMETHOD(VideoProcessorGetStreamOutputRate)(This,pVideoProcessor,StreamIndex,pOutputRate,pRepeatFrame,pCustomRate)	\
STDMETHOD(VideoProcessorGetStreamSourceRect)(This,pVideoProcessor,StreamIndex,pEnabled,pRect)	\
STDMETHOD(VideoProcessorGetStreamDestRect)(This,pVideoProcessor,StreamIndex,pEnabled,pRect)	\
STDMETHOD(VideoProcessorGetStreamAlpha)(This,pVideoProcessor,StreamIndex,pEnabled,pAlpha)	\
STDMETHOD(VideoProcessorGetStreamPalette)(This,pVideoProcessor,StreamIndex,Count,pEntries)	\
STDMETHOD(VideoProcessorGetStreamPixelAspectRatio)(This,pVideoProcessor,StreamIndex,pEnabled,pSourceAspectRatio,pDestinationAspectRatio)	\
STDMETHOD(VideoProcessorGetStreamLumaKey)(This,pVideoProcessor,StreamIndex,pEnabled,pLower,pUpper)	\
STDMETHOD(VideoProcessorGetStreamStereoFormat)(This,pVideoProcessor,StreamIndex,pEnable,pFormat,pLeftViewFrame0,pBaseViewFrame0,pFlipMode,MonoOffset)	\
STDMETHOD(VideoProcessorGetStreamAutoProcessingMode)(This,pVideoProcessor,StreamIndex,pEnabled)	\
STDMETHOD(VideoProcessorGetStreamFilter)(This,pVideoProcessor,StreamIndex,Filter,pEnabled,pLevel)	\
STDMETHOD(VideoProcessorGetStreamExtension)(This,pVideoProcessor,StreamIndex,pExtensionGuid,DataSize,pData)	\
STDMETHOD(VideoProcessorBlt)(This,pVideoProcessor,pView,OutputFrame,StreamCount,pStreams)	\
STDMETHOD(NegotiateCryptoSessionKeyExchange)(This,pCryptoSession,DataSize,pData)	\
STDMETHOD(EncryptionBlt)(This,pCryptoSession,pSrcSurface,pDstSurface,IVSize,pIV)	\
STDMETHOD(DecryptionBlt)(This,pCryptoSession,pSrcSurface,pDstSurface,pEncryptedBlockInfo,ContentKeySize,pContentKey,IVSize,pIV)	\
STDMETHOD(StartSessionKeyRefresh)(This,pCryptoSession,RandomNumberSize,pRandomNumber)	\
STDMETHOD(FinishSessionKeyRefresh)(This,pCryptoSession)	\
STDMETHOD(GetEncryptionBltKey)(This,pCryptoSession,KeySize,pReadbackKey)	\
STDMETHOD(NegotiateAuthenticatedChannelKeyExchange)(This,pChannel,DataSize,pData)	\
STDMETHOD(QueryAuthenticatedChannel)(This,pChannel,InputSize,pInput,OutputSize,pOutput)	\
STDMETHOD(ConfigureAuthenticatedChannel)(This,pChannel,InputSize,pInput,pOutput)	\
STDMETHOD(VideoProcessorSetStreamRotation)(This,pVideoProcessor,StreamIndex,Enable,Rotation)	\
STDMETHOD(VideoProcessorGetStreamRotation)(This,pVideoProcessor,StreamIndex,pEnable,pRotation)	\
STDMETHOD(SubmitDecoderBuffers1)(This,pDecoder,NumBuffers,pBufferDesc)	\
STDMETHOD(GetDataForNewHardwareKey)(This,pCryptoSession,PrivateInputSize,pPrivatInputData,pPrivateOutputData)	\
STDMETHOD(CheckCryptoSessionStatus)(This,pCryptoSession,pStatus)	\
STDMETHOD(DecoderEnableDownsampling)(This,pDecoder,InputColorSpace,pOutputDesc,ReferenceFrameCount)	\
STDMETHOD(DecoderUpdateDownsampling)(This,pDecoder,pOutputDesc)	\
STDMETHOD(VideoProcessorSetOutputColorSpace1)(This,pVideoProcessor,ColorSpace)	\
STDMETHOD(VideoProcessorSetOutputShaderUsage)(This,pVideoProcessor,ShaderUsage)	\
STDMETHOD(VideoProcessorGetOutputColorSpace1)(This,pVideoProcessor,pColorSpace)	\
STDMETHOD(VideoProcessorGetOutputShaderUsage)(This,pVideoProcessor,pShaderUsage)	\
STDMETHOD(VideoProcessorSetStreamColorSpace1)(This,pVideoProcessor,StreamIndex,ColorSpace)	\
STDMETHOD(VideoProcessorSetStreamMirror)(This,pVideoProcessor,StreamIndex,Enable,FlipHorizontal,FlipVertical)	\
STDMETHOD(VideoProcessorGetStreamColorSpace1)(This,pVideoProcessor,StreamIndex,pColorSpace)	\
STDMETHOD(VideoProcessorGetStreamMirror)(This,pVideoProcessor,StreamIndex,pEnable,pFlipHorizontal,pFlipVertical)	\
STDMETHOD(VideoProcessorGetBehaviorHints)(This,pVideoProcessor,OutputWidth,OutputHeight,OutputFormat,StreamCount,pStreams,pBehaviorHints)	\
STDMETHOD(VideoProcessorSetOutputHDRMetaData)(This,pVideoProcessor,Type,Size,pHDRMetaData)	\
STDMETHOD(VideoProcessorGetOutputHDRMetaData)(This,pVideoProcessor,pType,Size,pMetaData)	\
STDMETHOD(VideoProcessorSetStreamHDRMetaData)(This,pVideoProcessor,StreamIndex,Type,Size,pHDRMetaData)	\
STDMETHOD(VideoProcessorGetStreamHDRMetaData)(This,pVideoProcessor,StreamIndex,pType,Size,pMetaData)	\
"
)




D3D11_4.err := {}

