;File automatically generated by CrappyCppHeaderParser.ahk (Copyright@ peixoto)

Global D3D11_3 := {}
D3D11_3.IID_ID3D11Texture3D1 := "{0C711683-2853-4846-9BB0-F3E60639E46A}"
D3D11_3.IID_ID3D11RasterizerState2 := "{6fbd02fb-209f-46c4-b059-2ed15586a6ac}"
D3D11_3.IID_ID3D11ShaderResourceView1 := "{91308b87-9040-411d-8c67-c39253ce3802}"
D3D11_3.IID_ID3D11RenderTargetView1 := "{ffbe2e23-f011-418a-ac56-5ceed7c5b94b}"
D3D11_3.IID_ID3D11UnorderedAccessView1 := "{7b3b6153-a886-4544-ab37-6537c8500403}"
D3D11_3.IID_ID3D11Query1 := "{631b4766-36dc-461d-8db6-c47e13e60916}"
D3D11_3.IID_ID3D11DeviceContext3 := "{b4e3c01d-e79e-4637-91b2-510e9f4c9b8f}"
D3D11_3.IID_ID3D11Fence := "{affde9d1-1df7-4bb7-8a34-0f46251dab80}"
D3D11_3.IID_ID3D11DeviceContext4 := "{917600da-f58c-4c33-98d8-3e15b390fa24}"
D3D11_3.IID_ID3D11Device3 := "{A05C8C37-D2C6-4732-B3A0-9CE0B0DC9AE6}"

D3D11_3.ID3D11Device3 := {}
D3D11_3.ID3D11Device3.name := "ID3D11Device3"
D3D11_3.ID3D11Device3.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(CreateBuffer)(This,pDesc,pInitialData,ppBuffer)	\
STDMETHOD(CreateTexture1D)(This,pDesc,pInitialData,ppTexture1D)	\
STDMETHOD(CreateTexture2D)(This,pDesc,pInitialData,ppTexture2D)	\
STDMETHOD(CreateTexture3D)(This,pDesc,pInitialData,ppTexture3D)	\
STDMETHOD(CreateShaderResourceView)(This,pResource,pDesc,ppSRView)	\
STDMETHOD(CreateUnorderedAccessView)(This,pResource,pDesc,ppUAView)	\
STDMETHOD(CreateRenderTargetView)(This,pResource,pDesc,ppRTView)	\
STDMETHOD(CreateDepthStencilView)(This,pResource,pDesc,ppDepthStencilView)	\
STDMETHOD(CreateInputLayout)(This,pInputElementDescs,NumElements,pShaderBytecodeWithInputSignature,BytecodeLength,ppInputLayout)	\
STDMETHOD(CreateVertexShader)(This,pShaderBytecode,BytecodeLength,pClassLinkage,ppVertexShader)	\
STDMETHOD(CreateGeometryShader)(This,pShaderBytecode,BytecodeLength,pClassLinkage,ppGeometryShader)	\
STDMETHOD(CreateGeometryShaderWithStreamOutput)(This,pShaderBytecode,BytecodeLength,pSODeclaration,NumEntries,pBufferStrides,NumStrides,RasterizedStream,pClassLinkage,ppGeometryShader)	\
STDMETHOD(CreatePixelShader)(This,pShaderBytecode,BytecodeLength,pClassLinkage,ppPixelShader)	\
STDMETHOD(CreateHullShader)(This,pShaderBytecode,BytecodeLength,pClassLinkage,ppHullShader)	\
STDMETHOD(CreateDomainShader)(This,pShaderBytecode,BytecodeLength,pClassLinkage,ppDomainShader)	\
STDMETHOD(CreateComputeShader)(This,pShaderBytecode,BytecodeLength,pClassLinkage,ppComputeShader)	\
STDMETHOD(CreateClassLinkage)(This,ppLinkage)	\
STDMETHOD(CreateBlendState)(This,pBlendStateDesc,ppBlendState)	\
STDMETHOD(CreateDepthStencilState)(This,pDepthStencilDesc,ppDepthStencilState)	\
STDMETHOD(CreateRasterizerState)(This,pRasterizerDesc,ppRasterizerState)	\
STDMETHOD(CreateSamplerState)(This,pSamplerDesc,ppSamplerState)	\
STDMETHOD(CreateQuery)(This,pQueryDesc,ppQuery)	\
STDMETHOD(CreatePredicate)(This,pPredicateDesc,ppPredicate)	\
STDMETHOD(CreateCounter)(This,pCounterDesc,ppCounter)	\
STDMETHOD(CreateDeferredContext)(This,ContextFlags,ppDeferredContext)	\
STDMETHOD(OpenSharedResource)(This,hResource,ReturnedInterface,ppResource)	\
STDMETHOD(CheckFormatSupport)(This,Format,pFormatSupport)	\
STDMETHOD(CheckMultisampleQualityLevels)(This,Format,SampleCount,pNumQualityLevels)	\
STDMETHOD(CheckCounterInfo)(This,pCounterInfo)	\
STDMETHOD(CheckCounter)(This,pDesc,pType,pActiveCounters,szName,pNameLength,szUnits,pUnitsLength,szDescription,pDescriptionLength)	\
STDMETHOD(CheckFeatureSupport)(This,Feature,pFeatureSupportData,FeatureSupportDataSize)	\
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)	\
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)	\
STDMETHOD(GetFeatureLevel)(This)	\
STDMETHOD(GetCreationFlags)(This)	\
STDMETHOD(GetDeviceRemovedReason)(This)	\
STDMETHOD(GetImmediateContext)(This,ppImmediateContext)	\
STDMETHOD(SetExceptionMode)(This,RaiseFlags)	\
STDMETHOD(GetExceptionMode)(This)	\
STDMETHOD(GetImmediateContext1)(This,ppImmediateContext)	\
STDMETHOD(CreateDeferredContext1)(This,ContextFlags,ppDeferredContext)	\
STDMETHOD(CreateBlendState1)(This,pBlendStateDesc,ppBlendState)	\
STDMETHOD(CreateRasterizerState1)(This,pRasterizerDesc,ppRasterizerState)	\
STDMETHOD(CreateDeviceContextState)(This,Flags,pFeatureLevels,FeatureLevels,SDKVersion,EmulatedInterface,pChosenFeatureLevel,ppContextState)	\
STDMETHOD(OpenSharedResource1)(This,hResource,returnedInterface,ppResource)	\
STDMETHOD(OpenSharedResourceByName)(This,lpName,dwDesiredAccess,returnedInterface,ppResource)	\
STDMETHOD(GetImmediateContext2)(This,ppImmediateContext)	\
STDMETHOD(CreateDeferredContext2)(This,ContextFlags,ppDeferredContext)	\
STDMETHOD(GetResourceTiling)(This,pTiledResource,pNumTilesForEntireResource,pPackedMipDesc,pStandardTileShapeForNonPackedMips,pNumSubresourceTilings,FirstSubresourceTilingToGet,pSubresourceTilingsForNonPackedMips)	\
STDMETHOD(CheckMultisampleQualityLevels1)(This,Format,SampleCount,Flags,pNumQualityLevels)	\
STDMETHOD(CreateTexture2D1)(This,pDesc1,pInitialData,ppTexture2D)	\
STDMETHOD(CreateTexture3D1)(This,pDesc1,pInitialData,ppTexture3D)	\
STDMETHOD(CreateRasterizerState2)(This,pRasterizerDesc,ppRasterizerState)	\
STDMETHOD(CreateShaderResourceView1)(This,pResource,pDesc1,ppSRView1)	\
STDMETHOD(CreateUnorderedAccessView1)(This,pResource,pDesc1,ppUAView1)	\
STDMETHOD(CreateRenderTargetView1)(This,pResource,pDesc1,ppRTView1)	\
STDMETHOD(CreateQuery1)(This,pQueryDesc1,ppQuery1)	\
STDMETHOD(GetImmediateContext3)(This,ppImmediateContext)	\
STDMETHOD(CreateDeferredContext3)(This,ContextFlags,ppDeferredContext)	\
STDMETHOD(WriteToSubresource)(This,pDstResource,DstSubresource,pDstBox,pSrcData,SrcRowPitch,SrcDepthPitch)	\
STDMETHOD(ReadFromSubresource)(This,pDstData,DstRowPitch,DstDepthPitch,pSrcResource,SrcSubresource,pSrcBox)	\
"
)

D3D11_3.ID3D11DeviceContext3 := {}
D3D11_3.ID3D11DeviceContext3.name := "ID3D11DeviceContext3"
D3D11_3.ID3D11DeviceContext3.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(GetDevice)(This,ppDevice)	\
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)	\
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)	\
STDMETHOD(VSSetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(PSSetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(PSSetShader)(This,pPixelShader,ppClassInstances,NumClassInstances)	\
STDMETHOD(PSSetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(VSSetShader)(This,pVertexShader,ppClassInstances,NumClassInstances)	\
STDMETHOD(DrawIndexed)(This,IndexCount,StartIndexLocation,BaseVertexLocation)	\
STDMETHOD(Draw)(This,VertexCount,StartVertexLocation)	\
STDMETHOD(Map)(This,pResource,Subresource,MapType,MapFlags,pMappedResource)	\
STDMETHOD(Unmap)(This,pResource,Subresource)	\
STDMETHOD(PSSetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(IASetInputLayout)(This,pInputLayout)	\
STDMETHOD(IASetVertexBuffers)(This,StartSlot,NumBuffers,ppVertexBuffers,pStrides,pOffsets)	\
STDMETHOD(IASetIndexBuffer)(This,pIndexBuffer,Format,Offset)	\
STDMETHOD(DrawIndexedInstanced)(This,IndexCountPerInstance,InstanceCount,StartIndexLocation,BaseVertexLocation,StartInstanceLocation)	\
STDMETHOD(DrawInstanced)(This,VertexCountPerInstance,InstanceCount,StartVertexLocation,StartInstanceLocation)	\
STDMETHOD(GSSetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(GSSetShader)(This,pShader,ppClassInstances,NumClassInstances)	\
STDMETHOD(IASetPrimitiveTopology)(This,Topology)	\
STDMETHOD(VSSetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(VSSetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(Begin)(This,pAsync)	\
STDMETHOD(End)(This,pAsync)	\
STDMETHOD(GetData)(This,pAsync,pData,DataSize,GetDataFlags)	\
STDMETHOD(SetPredication)(This,pPredicate,PredicateValue)	\
STDMETHOD(GSSetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(GSSetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(OMSetRenderTargets)(This,NumViews,ppRenderTargetViews,pDepthStencilView)	\
STDMETHOD(OMSetRenderTargetsAndUnorderedAccessViews)(This,NumRTVs,ppRenderTargetViews,pDepthStencilView,UAVStartSlot,NumUAVs,ppUnorderedAccessViews,pUAVInitialCounts)	\
STDMETHOD(OMSetBlendState)(This,pBlendState,BlendFactor,SampleMask)	\
STDMETHOD(OMSetDepthStencilState)(This,pDepthStencilState,StencilRef)	\
STDMETHOD(SOSetTargets)(This,NumBuffers,ppSOTargets,pOffsets)	\
STDMETHOD(DrawAuto)(This)	\
STDMETHOD(DrawIndexedInstancedIndirect)(This,pBufferForArgs,AlignedByteOffsetForArgs)	\
STDMETHOD(DrawInstancedIndirect)(This,pBufferForArgs,AlignedByteOffsetForArgs)	\
STDMETHOD(Dispatch)(This,ThreadGroupCountX,ThreadGroupCountY,ThreadGroupCountZ)	\
STDMETHOD(DispatchIndirect)(This,pBufferForArgs,AlignedByteOffsetForArgs)	\
STDMETHOD(RSSetState)(This,pRasterizerState)	\
STDMETHOD(RSSetViewports)(This,NumViewports,pViewports)	\
STDMETHOD(RSSetScissorRects)(This,NumRects,pRects)	\
STDMETHOD(CopySubresourceRegion)(This,pDstResource,DstSubresource,DstX,DstY,DstZ,pSrcResource,SrcSubresource,pSrcBox)	\
STDMETHOD(CopyResource)(This,pDstResource,pSrcResource)	\
STDMETHOD(UpdateSubresource)(This,pDstResource,DstSubresource,pDstBox,pSrcData,SrcRowPitch,SrcDepthPitch)	\
STDMETHOD(CopyStructureCount)(This,pDstBuffer,DstAlignedByteOffset,pSrcView)	\
STDMETHOD(ClearRenderTargetView)(This,pRenderTargetView,ColorRGBA)	\
STDMETHOD(ClearUnorderedAccessViewUint)(This,pUnorderedAccessView,Values)	\
STDMETHOD(ClearUnorderedAccessViewFloat)(This,pUnorderedAccessView,Values)	\
STDMETHOD(ClearDepthStencilView)(This,pDepthStencilView,ClearFlags,Depth,Stencil)	\
STDMETHOD(GenerateMips)(This,pShaderResourceView)	\
STDMETHOD(SetResourceMinLOD)(This,pResource,MinLOD)	\
STDMETHOD(GetResourceMinLOD)(This,pResource)	\
STDMETHOD(ResolveSubresource)(This,pDstResource,DstSubresource,pSrcResource,SrcSubresource,Format)	\
STDMETHOD(ExecuteCommandList)(This,pCommandList,RestoreContextState)	\
STDMETHOD(HSSetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(HSSetShader)(This,pHullShader,ppClassInstances,NumClassInstances)	\
STDMETHOD(HSSetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(HSSetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(DSSetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(DSSetShader)(This,pDomainShader,ppClassInstances,NumClassInstances)	\
STDMETHOD(DSSetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(DSSetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(CSSetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(CSSetUnorderedAccessViews)(This,StartSlot,NumUAVs,ppUnorderedAccessViews,pUAVInitialCounts)	\
STDMETHOD(CSSetShader)(This,pComputeShader,ppClassInstances,NumClassInstances)	\
STDMETHOD(CSSetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(CSSetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(VSGetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(PSGetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(PSGetShader)(This,ppPixelShader,ppClassInstances,pNumClassInstances)	\
STDMETHOD(PSGetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(VSGetShader)(This,ppVertexShader,ppClassInstances,pNumClassInstances)	\
STDMETHOD(PSGetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(IAGetInputLayout)(This,ppInputLayout)	\
STDMETHOD(IAGetVertexBuffers)(This,StartSlot,NumBuffers,ppVertexBuffers,pStrides,pOffsets)	\
STDMETHOD(IAGetIndexBuffer)(This,pIndexBuffer,Format,Offset)	\
STDMETHOD(GSGetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(GSGetShader)(This,ppGeometryShader,ppClassInstances,pNumClassInstances)	\
STDMETHOD(IAGetPrimitiveTopology)(This,pTopology)	\
STDMETHOD(VSGetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(VSGetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(GetPredication)(This,ppPredicate,pPredicateValue)	\
STDMETHOD(GSGetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(GSGetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(OMGetRenderTargets)(This,NumViews,ppRenderTargetViews,ppDepthStencilView)	\
STDMETHOD(OMGetRenderTargetsAndUnorderedAccessViews)(This,NumRTVs,ppRenderTargetViews,ppDepthStencilView,UAVStartSlot,NumUAVs,ppUnorderedAccessViews)	\
STDMETHOD(OMGetBlendState)(This,ppBlendState,BlendFactor,pSampleMask)	\
STDMETHOD(OMGetDepthStencilState)(This,ppDepthStencilState,pStencilRef)	\
STDMETHOD(SOGetTargets)(This,NumBuffers,ppSOTargets)	\
STDMETHOD(RSGetState)(This,ppRasterizerState)	\
STDMETHOD(RSGetViewports)(This,pNumViewports,pViewports)	\
STDMETHOD(RSGetScissorRects)(This,pNumRects,pRects)	\
STDMETHOD(HSGetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(HSGetShader)(This,ppHullShader,ppClassInstances,pNumClassInstances)	\
STDMETHOD(HSGetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(HSGetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(DSGetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(DSGetShader)(This,ppDomainShader,ppClassInstances,pNumClassInstances)	\
STDMETHOD(DSGetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(DSGetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(CSGetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(CSGetUnorderedAccessViews)(This,StartSlot,NumUAVs,ppUnorderedAccessViews)	\
STDMETHOD(CSGetShader)(This,ppComputeShader,ppClassInstances,pNumClassInstances)	\
STDMETHOD(CSGetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(CSGetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(ClearState)(This)	\
STDMETHOD(Flush)(This)	\
STDMETHOD(GetType)(This)	\
STDMETHOD(GetContextFlags)(This)	\
STDMETHOD(FinishCommandList)(This,RestoreDeferredContextState,ppCommandList)	\
STDMETHOD(CopySubresourceRegion1)(This,pDstResource,DstSubresource,DstX,DstY,DstZ,pSrcResource,SrcSubresource,pSrcBox,CopyFlags)	\
STDMETHOD(UpdateSubresource1)(This,pDstResource,DstSubresource,pDstBox,pSrcData,SrcRowPitch,SrcDepthPitch,CopyFlags)	\
STDMETHOD(DiscardResource)(This,pResource)	\
STDMETHOD(DiscardView)(This,pResourceView)	\
STDMETHOD(VSSetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(HSSetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(DSSetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(GSSetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(PSSetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(CSSetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(VSGetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(HSGetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(DSGetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(GSGetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(PSGetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(CSGetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(SwapDeviceContextState)(This,pState,ppPreviousState)	\
STDMETHOD(ClearView)(This,pView,Color,pRect,NumRects)	\
STDMETHOD(DiscardView1)(This,pResourceView,pRects,NumRects)	\
STDMETHOD(UpdateTileMappings)(This,pTiledResource,NumTiledResourceRegions,pTiledResourceRegionStartCoordinates,pTiledResourceRegionSizes,pTilePool,NumRanges,pRangeFlags,pTilePoolStartOffsets,pRangeTileCounts,Flags)	\
STDMETHOD(CopyTileMappings)(This,pDestTiledResource,pDestRegionStartCoordinate,pSourceTiledResource,pSourceRegionStartCoordinate,pTileRegionSize,Flags)	\
STDMETHOD(CopyTiles)(This,pTiledResource,pTileRegionStartCoordinate,pTileRegionSize,pBuffer,BufferStartOffsetInBytes,Flags)	\
STDMETHOD(UpdateTiles)(This,pDestTiledResource,pDestTileRegionStartCoordinate,pDestTileRegionSize,pSourceTileData,Flags)	\
STDMETHOD(ResizeTilePool)(This,pTilePool,NewSizeInBytes)	\
STDMETHOD(TiledResourceBarrier)(This,pTiledResourceOrViewAccessBeforeBarrier,pTiledResourceOrViewAccessAfterBarrier)	\
STDMETHOD(IsAnnotationEnabled)(This)	\
STDMETHOD(SetMarkerInt)(This,pLabel,Data)	\
STDMETHOD(BeginEventInt)(This,pLabel,Data)	\
STDMETHOD(EndEvent)(This)	\
STDMETHOD(Flush1)(This,ContextType,hEvent)	\
STDMETHOD(SetHardwareProtectionState)(This,HwProtectionEnable)	\
STDMETHOD(GetHardwareProtectionState)(This,pHwProtectionEnable)	\
"
)

D3D11_3.ID3D11DeviceContext4 := {}
D3D11_3.ID3D11DeviceContext4.name := "ID3D11DeviceContext4"
D3D11_3.ID3D11DeviceContext4.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(GetDevice)(This,ppDevice)	\
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)	\
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)	\
STDMETHOD(VSSetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(PSSetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(PSSetShader)(This,pPixelShader,ppClassInstances,NumClassInstances)	\
STDMETHOD(PSSetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(VSSetShader)(This,pVertexShader,ppClassInstances,NumClassInstances)	\
STDMETHOD(DrawIndexed)(This,IndexCount,StartIndexLocation,BaseVertexLocation)	\
STDMETHOD(Draw)(This,VertexCount,StartVertexLocation)	\
STDMETHOD(Map)(This,pResource,Subresource,MapType,MapFlags,pMappedResource)	\
STDMETHOD(Unmap)(This,pResource,Subresource)	\
STDMETHOD(PSSetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(IASetInputLayout)(This,pInputLayout)	\
STDMETHOD(IASetVertexBuffers)(This,StartSlot,NumBuffers,ppVertexBuffers,pStrides,pOffsets)	\
STDMETHOD(IASetIndexBuffer)(This,pIndexBuffer,Format,Offset)	\
STDMETHOD(DrawIndexedInstanced)(This,IndexCountPerInstance,InstanceCount,StartIndexLocation,BaseVertexLocation,StartInstanceLocation)	\
STDMETHOD(DrawInstanced)(This,VertexCountPerInstance,InstanceCount,StartVertexLocation,StartInstanceLocation)	\
STDMETHOD(GSSetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(GSSetShader)(This,pShader,ppClassInstances,NumClassInstances)	\
STDMETHOD(IASetPrimitiveTopology)(This,Topology)	\
STDMETHOD(VSSetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(VSSetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(Begin)(This,pAsync)	\
STDMETHOD(End)(This,pAsync)	\
STDMETHOD(GetData)(This,pAsync,pData,DataSize,GetDataFlags)	\
STDMETHOD(SetPredication)(This,pPredicate,PredicateValue)	\
STDMETHOD(GSSetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(GSSetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(OMSetRenderTargets)(This,NumViews,ppRenderTargetViews,pDepthStencilView)	\
STDMETHOD(OMSetRenderTargetsAndUnorderedAccessViews)(This,NumRTVs,ppRenderTargetViews,pDepthStencilView,UAVStartSlot,NumUAVs,ppUnorderedAccessViews,pUAVInitialCounts)	\
STDMETHOD(OMSetBlendState)(This,pBlendState,BlendFactor,SampleMask)	\
STDMETHOD(OMSetDepthStencilState)(This,pDepthStencilState,StencilRef)	\
STDMETHOD(SOSetTargets)(This,NumBuffers,ppSOTargets,pOffsets)	\
STDMETHOD(DrawAuto)(This)	\
STDMETHOD(DrawIndexedInstancedIndirect)(This,pBufferForArgs,AlignedByteOffsetForArgs)	\
STDMETHOD(DrawInstancedIndirect)(This,pBufferForArgs,AlignedByteOffsetForArgs)	\
STDMETHOD(Dispatch)(This,ThreadGroupCountX,ThreadGroupCountY,ThreadGroupCountZ)	\
STDMETHOD(DispatchIndirect)(This,pBufferForArgs,AlignedByteOffsetForArgs)	\
STDMETHOD(RSSetState)(This,pRasterizerState)	\
STDMETHOD(RSSetViewports)(This,NumViewports,pViewports)	\
STDMETHOD(RSSetScissorRects)(This,NumRects,pRects)	\
STDMETHOD(CopySubresourceRegion)(This,pDstResource,DstSubresource,DstX,DstY,DstZ,pSrcResource,SrcSubresource,pSrcBox)	\
STDMETHOD(CopyResource)(This,pDstResource,pSrcResource)	\
STDMETHOD(UpdateSubresource)(This,pDstResource,DstSubresource,pDstBox,pSrcData,SrcRowPitch,SrcDepthPitch)	\
STDMETHOD(CopyStructureCount)(This,pDstBuffer,DstAlignedByteOffset,pSrcView)	\
STDMETHOD(ClearRenderTargetView)(This,pRenderTargetView,ColorRGBA)	\
STDMETHOD(ClearUnorderedAccessViewUint)(This,pUnorderedAccessView,Values)	\
STDMETHOD(ClearUnorderedAccessViewFloat)(This,pUnorderedAccessView,Values)	\
STDMETHOD(ClearDepthStencilView)(This,pDepthStencilView,ClearFlags,Depth,Stencil)	\
STDMETHOD(GenerateMips)(This,pShaderResourceView)	\
STDMETHOD(SetResourceMinLOD)(This,pResource,MinLOD)	\
STDMETHOD(GetResourceMinLOD)(This,pResource)	\
STDMETHOD(ResolveSubresource)(This,pDstResource,DstSubresource,pSrcResource,SrcSubresource,Format)	\
STDMETHOD(ExecuteCommandList)(This,pCommandList,RestoreContextState)	\
STDMETHOD(HSSetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(HSSetShader)(This,pHullShader,ppClassInstances,NumClassInstances)	\
STDMETHOD(HSSetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(HSSetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(DSSetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(DSSetShader)(This,pDomainShader,ppClassInstances,NumClassInstances)	\
STDMETHOD(DSSetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(DSSetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(CSSetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(CSSetUnorderedAccessViews)(This,StartSlot,NumUAVs,ppUnorderedAccessViews,pUAVInitialCounts)	\
STDMETHOD(CSSetShader)(This,pComputeShader,ppClassInstances,NumClassInstances)	\
STDMETHOD(CSSetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(CSSetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(VSGetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(PSGetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(PSGetShader)(This,ppPixelShader,ppClassInstances,pNumClassInstances)	\
STDMETHOD(PSGetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(VSGetShader)(This,ppVertexShader,ppClassInstances,pNumClassInstances)	\
STDMETHOD(PSGetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(IAGetInputLayout)(This,ppInputLayout)	\
STDMETHOD(IAGetVertexBuffers)(This,StartSlot,NumBuffers,ppVertexBuffers,pStrides,pOffsets)	\
STDMETHOD(IAGetIndexBuffer)(This,pIndexBuffer,Format,Offset)	\
STDMETHOD(GSGetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(GSGetShader)(This,ppGeometryShader,ppClassInstances,pNumClassInstances)	\
STDMETHOD(IAGetPrimitiveTopology)(This,pTopology)	\
STDMETHOD(VSGetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(VSGetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(GetPredication)(This,ppPredicate,pPredicateValue)	\
STDMETHOD(GSGetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(GSGetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(OMGetRenderTargets)(This,NumViews,ppRenderTargetViews,ppDepthStencilView)	\
STDMETHOD(OMGetRenderTargetsAndUnorderedAccessViews)(This,NumRTVs,ppRenderTargetViews,ppDepthStencilView,UAVStartSlot,NumUAVs,ppUnorderedAccessViews)	\
STDMETHOD(OMGetBlendState)(This,ppBlendState,BlendFactor,pSampleMask)	\
STDMETHOD(OMGetDepthStencilState)(This,ppDepthStencilState,pStencilRef)	\
STDMETHOD(SOGetTargets)(This,NumBuffers,ppSOTargets)	\
STDMETHOD(RSGetState)(This,ppRasterizerState)	\
STDMETHOD(RSGetViewports)(This,pNumViewports,pViewports)	\
STDMETHOD(RSGetScissorRects)(This,pNumRects,pRects)	\
STDMETHOD(HSGetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(HSGetShader)(This,ppHullShader,ppClassInstances,pNumClassInstances)	\
STDMETHOD(HSGetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(HSGetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(DSGetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(DSGetShader)(This,ppDomainShader,ppClassInstances,pNumClassInstances)	\
STDMETHOD(DSGetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(DSGetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(CSGetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(CSGetUnorderedAccessViews)(This,StartSlot,NumUAVs,ppUnorderedAccessViews)	\
STDMETHOD(CSGetShader)(This,ppComputeShader,ppClassInstances,pNumClassInstances)	\
STDMETHOD(CSGetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(CSGetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(ClearState)(This)	\
STDMETHOD(Flush)(This)	\
STDMETHOD(GetType)(This)	\
STDMETHOD(GetContextFlags)(This)	\
STDMETHOD(FinishCommandList)(This,RestoreDeferredContextState,ppCommandList)	\
STDMETHOD(CopySubresourceRegion1)(This,pDstResource,DstSubresource,DstX,DstY,DstZ,pSrcResource,SrcSubresource,pSrcBox,CopyFlags)	\
STDMETHOD(UpdateSubresource1)(This,pDstResource,DstSubresource,pDstBox,pSrcData,SrcRowPitch,SrcDepthPitch,CopyFlags)	\
STDMETHOD(DiscardResource)(This,pResource)	\
STDMETHOD(DiscardView)(This,pResourceView)	\
STDMETHOD(VSSetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(HSSetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(DSSetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(GSSetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(PSSetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(CSSetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(VSGetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(HSGetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(DSGetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(GSGetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(PSGetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(CSGetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(SwapDeviceContextState)(This,pState,ppPreviousState)	\
STDMETHOD(ClearView)(This,pView,Color,pRect,NumRects)	\
STDMETHOD(DiscardView1)(This,pResourceView,pRects,NumRects)	\
STDMETHOD(UpdateTileMappings)(This,pTiledResource,NumTiledResourceRegions,pTiledResourceRegionStartCoordinates,pTiledResourceRegionSizes,pTilePool,NumRanges,pRangeFlags,pTilePoolStartOffsets,pRangeTileCounts,Flags)	\
STDMETHOD(CopyTileMappings)(This,pDestTiledResource,pDestRegionStartCoordinate,pSourceTiledResource,pSourceRegionStartCoordinate,pTileRegionSize,Flags)	\
STDMETHOD(CopyTiles)(This,pTiledResource,pTileRegionStartCoordinate,pTileRegionSize,pBuffer,BufferStartOffsetInBytes,Flags)	\
STDMETHOD(UpdateTiles)(This,pDestTiledResource,pDestTileRegionStartCoordinate,pDestTileRegionSize,pSourceTileData,Flags)	\
STDMETHOD(ResizeTilePool)(This,pTilePool,NewSizeInBytes)	\
STDMETHOD(TiledResourceBarrier)(This,pTiledResourceOrViewAccessBeforeBarrier,pTiledResourceOrViewAccessAfterBarrier)	\
STDMETHOD(IsAnnotationEnabled)(This)	\
STDMETHOD(SetMarkerInt)(This,pLabel,Data)	\
STDMETHOD(BeginEventInt)(This,pLabel,Data)	\
STDMETHOD(EndEvent)(This)	\
STDMETHOD(Flush1)(This,ContextType,hEvent)	\
STDMETHOD(SetHardwareProtectionState)(This,HwProtectionEnable)	\
STDMETHOD(GetHardwareProtectionState)(This,pHwProtectionEnable)	\
STDMETHOD(Signal)(This,pFence,Value)	\
STDMETHOD(Wait)(This,pFence,Value)	\
"
)

D3D11_3.ID3D11Fence := {}
D3D11_3.ID3D11Fence.name := "ID3D11Fence"
D3D11_3.ID3D11Fence.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(GetDevice)(This,ppDevice)	\
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)	\
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)	\
STDMETHOD(CreateSharedHandle)(This,pAttributes,dwAccess,lpName,pHandle)	\
STDMETHOD(GetCompletedValue)(This)	\
STDMETHOD(SetEventOnCompletion)(This,Value,hEvent)	\
"
)

D3D11_3.ID3D11Query1 := {}
D3D11_3.ID3D11Query1.name := "ID3D11Query1"
D3D11_3.ID3D11Query1.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(GetDevice)(This,ppDevice)	\
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)	\
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)	\
STDMETHOD(GetDataSize)(This)	\
STDMETHOD(GetDesc)(This,pDesc)	\
STDMETHOD(GetDesc1)(This,pDesc1)	\
"
)

D3D11_3.ID3D11RasterizerState2 := {}
D3D11_3.ID3D11RasterizerState2.name := "ID3D11RasterizerState2"
D3D11_3.ID3D11RasterizerState2.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(GetDevice)(This,ppDevice)	\
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)	\
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)	\
STDMETHOD(GetDesc)(This,pDesc)	\
STDMETHOD(GetDesc1)(This,pDesc)	\
STDMETHOD(GetDesc2)(This,pDesc)	\
"
)

D3D11_3.ID3D11RenderTargetView1 := {}
D3D11_3.ID3D11RenderTargetView1.name := "ID3D11RenderTargetView1"
D3D11_3.ID3D11RenderTargetView1.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(GetDevice)(This,ppDevice)	\
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)	\
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)	\
STDMETHOD(GetResource)(This,ppResource)	\
STDMETHOD(GetDesc)(This,pDesc)	\
STDMETHOD(GetDesc1)(This,pDesc1)	\
"
)

D3D11_3.ID3D11ShaderResourceView1 := {}
D3D11_3.ID3D11ShaderResourceView1.name := "ID3D11ShaderResourceView1"
D3D11_3.ID3D11ShaderResourceView1.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(GetDevice)(This,ppDevice)	\
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)	\
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)	\
STDMETHOD(GetResource)(This,ppResource)	\
STDMETHOD(GetDesc)(This,pDesc)	\
STDMETHOD(GetDesc1)(This,pDesc1)	\
"
)

D3D11_3.ID3D11Texture3D1 := {}
D3D11_3.ID3D11Texture3D1.name := "ID3D11Texture3D1"
D3D11_3.ID3D11Texture3D1.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(GetDevice)(This,ppDevice)	\
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)	\
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)	\
STDMETHOD(GetType)(This,pResourceDimension)	\
STDMETHOD(SetEvictionPriority)(This,EvictionPriority)	\
STDMETHOD(GetEvictionPriority)(This)	\
STDMETHOD(GetDesc)(This,pDesc)	\
STDMETHOD(GetDesc1)(This,pDesc)	\
"
)

D3D11_3.ID3D11UnorderedAccessView1 := {}
D3D11_3.ID3D11UnorderedAccessView1.name := "ID3D11UnorderedAccessView1"
D3D11_3.ID3D11UnorderedAccessView1.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(GetDevice)(This,ppDevice)	\
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)	\
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)	\
STDMETHOD(GetResource)(This,ppResource)	\
STDMETHOD(GetDesc)(This,pDesc)	\
STDMETHOD(GetDesc1)(This,pDesc1)	\
"
)



Global D3D11_TEXTURE_LAYOUT_ROW_MAJOR := 1
Global D3D11_TEXTURE_LAYOUT_64K_STANDARD_SWIZZLE := 2
Global D3D11_CONSERVATIVE_RASTERIZATION_MODE_ON := 1
Global D3D11_FENCE_FLAG_NONE := 0x1
Global D3D11_FENCE_FLAG_SHARED := 0x2
Global D3D11_FENCE_FLAG_SHARED_CROSS_ADAPTER := 0x4

D3D11_3.err := {}

