;File automatically generated by CrappyCppHeaderParser.ahk (Copyright@ peixoto)

Global D3D11_1 := {}
D3D11_1.IID_ID3D11RasterizerState1 := "{1217d7a6-5039-418c-b042-9cbe256afd6e}"
D3D11_1.IID_ID3DDeviceContextState := "{5c1e0d8a-7c23-48f9-8c59-a92958ceff11}"
D3D11_1.IID_ID3D11DeviceContext1 := "{bb2c6faa-b5fb-4082-8e6b-388b8cfa90e1}"
D3D11_1.IID_ID3D11VideoContext1 := "{A7F026DA-A5F8-4487-A564-15E34357651E}"
D3D11_1.IID_ID3D11VideoDevice1 := "{29DA1D51-1321-4454-804B-F5FC9F861F0F}"
D3D11_1.IID_ID3D11VideoProcessorEnumerator1 := "{465217F2-5568-43CF-B5B9-F61D54531CA1}"
D3D11_1.IID_ID3D11Device1 := "{a04bfb29-08ef-43d6-a49c-a9bdbdcbe686}"
D3D11_1.IID_ID3DUserDefinedAnnotation := "{b2daad8b-03d4-4dbf-95eb-32ab4b63d0ab}"

D3D11_1.ID3D11Device1 := {}
D3D11_1.ID3D11Device1.name := "ID3D11Device1"
D3D11_1.ID3D11Device1.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(CreateBuffer)(This,pDesc,pInitialData,ppBuffer)	\
STDMETHOD(CreateTexture1D)(This,pDesc,pInitialData,ppTexture1D)	\
STDMETHOD(CreateTexture2D)(This,pDesc,pInitialData,ppTexture2D)	\
STDMETHOD(CreateTexture3D)(This,pDesc,pInitialData,ppTexture3D)	\
STDMETHOD(CreateShaderResourceView)(This,pResource,pDesc,ppSRView)	\
STDMETHOD(CreateUnorderedAccessView)(This,pResource,pDesc,ppUAView)	\
STDMETHOD(CreateRenderTargetView)(This,pResource,pDesc,ppRTView)	\
STDMETHOD(CreateDepthStencilView)(This,pResource,pDesc,ppDepthStencilView)	\
STDMETHOD(CreateInputLayout)(This,pInputElementDescs,NumElements,pShaderBytecodeWithInputSignature,BytecodeLength,ppInputLayout)	\
STDMETHOD(CreateVertexShader)(This,pShaderBytecode,BytecodeLength,pClassLinkage,ppVertexShader)	\
STDMETHOD(CreateGeometryShader)(This,pShaderBytecode,BytecodeLength,pClassLinkage,ppGeometryShader)	\
STDMETHOD(CreateGeometryShaderWithStreamOutput)(This,pShaderBytecode,BytecodeLength,pSODeclaration,NumEntries,pBufferStrides,NumStrides,RasterizedStream,pClassLinkage,ppGeometryShader)	\
STDMETHOD(CreatePixelShader)(This,pShaderBytecode,BytecodeLength,pClassLinkage,ppPixelShader)	\
STDMETHOD(CreateHullShader)(This,pShaderBytecode,BytecodeLength,pClassLinkage,ppHullShader)	\
STDMETHOD(CreateDomainShader)(This,pShaderBytecode,BytecodeLength,pClassLinkage,ppDomainShader)	\
STDMETHOD(CreateComputeShader)(This,pShaderBytecode,BytecodeLength,pClassLinkage,ppComputeShader)	\
STDMETHOD(CreateClassLinkage)(This,ppLinkage)	\
STDMETHOD(CreateBlendState)(This,pBlendStateDesc,ppBlendState)	\
STDMETHOD(CreateDepthStencilState)(This,pDepthStencilDesc,ppDepthStencilState)	\
STDMETHOD(CreateRasterizerState)(This,pRasterizerDesc,ppRasterizerState)	\
STDMETHOD(CreateSamplerState)(This,pSamplerDesc,ppSamplerState)	\
STDMETHOD(CreateQuery)(This,pQueryDesc,ppQuery)	\
STDMETHOD(CreatePredicate)(This,pPredicateDesc,ppPredicate)	\
STDMETHOD(CreateCounter)(This,pCounterDesc,ppCounter)	\
STDMETHOD(CreateDeferredContext)(This,ContextFlags,ppDeferredContext)	\
STDMETHOD(OpenSharedResource)(This,hResource,ReturnedInterface,ppResource)	\
STDMETHOD(CheckFormatSupport)(This,Format,pFormatSupport)	\
STDMETHOD(CheckMultisampleQualityLevels)(This,Format,SampleCount,pNumQualityLevels)	\
STDMETHOD(CheckCounterInfo)(This,pCounterInfo)	\
STDMETHOD(CheckCounter)(This,pDesc,pType,pActiveCounters,szName,pNameLength,szUnits,pUnitsLength,szDescription,pDescriptionLength)	\
STDMETHOD(CheckFeatureSupport)(This,Feature,pFeatureSupportData,FeatureSupportDataSize)	\
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)	\
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)	\
STDMETHOD(GetFeatureLevel)(This)	\
STDMETHOD(GetCreationFlags)(This)	\
STDMETHOD(GetDeviceRemovedReason)(This)	\
STDMETHOD(GetImmediateContext)(This,ppImmediateContext)	\
STDMETHOD(SetExceptionMode)(This,RaiseFlags)	\
STDMETHOD(GetExceptionMode)(This)	\
STDMETHOD(GetImmediateContext1)(This,ppImmediateContext)	\
STDMETHOD(CreateDeferredContext1)(This,ContextFlags,ppDeferredContext)	\
STDMETHOD(CreateBlendState1)(This,pBlendStateDesc,ppBlendState)	\
STDMETHOD(CreateRasterizerState1)(This,pRasterizerDesc,ppRasterizerState)	\
STDMETHOD(CreateDeviceContextState)(This,Flags,pFeatureLevels,FeatureLevels,SDKVersion,EmulatedInterface,pChosenFeatureLevel,ppContextState)	\
STDMETHOD(OpenSharedResource1)(This,hResource,returnedInterface,ppResource)	\
STDMETHOD(OpenSharedResourceByName)(This,lpName,dwDesiredAccess,returnedInterface,ppResource)	\
"
)

D3D11_1.ID3D11DeviceContext1 := {}
D3D11_1.ID3D11DeviceContext1.name := "ID3D11DeviceContext1"
D3D11_1.ID3D11DeviceContext1.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(GetDevice)(This,ppDevice)	\
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)	\
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)	\
STDMETHOD(VSSetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(PSSetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(PSSetShader)(This,pPixelShader,ppClassInstances,NumClassInstances)	\
STDMETHOD(PSSetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(VSSetShader)(This,pVertexShader,ppClassInstances,NumClassInstances)	\
STDMETHOD(DrawIndexed)(This,IndexCount,StartIndexLocation,BaseVertexLocation)	\
STDMETHOD(Draw)(This,VertexCount,StartVertexLocation)	\
STDMETHOD(Map)(This,pResource,Subresource,MapType,MapFlags,pMappedResource)	\
STDMETHOD(Unmap)(This,pResource,Subresource)	\
STDMETHOD(PSSetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(IASetInputLayout)(This,pInputLayout)	\
STDMETHOD(IASetVertexBuffers)(This,StartSlot,NumBuffers,ppVertexBuffers,pStrides,pOffsets)	\
STDMETHOD(IASetIndexBuffer)(This,pIndexBuffer,Format,Offset)	\
STDMETHOD(DrawIndexedInstanced)(This,IndexCountPerInstance,InstanceCount,StartIndexLocation,BaseVertexLocation,StartInstanceLocation)	\
STDMETHOD(DrawInstanced)(This,VertexCountPerInstance,InstanceCount,StartVertexLocation,StartInstanceLocation)	\
STDMETHOD(GSSetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(GSSetShader)(This,pShader,ppClassInstances,NumClassInstances)	\
STDMETHOD(IASetPrimitiveTopology)(This,Topology)	\
STDMETHOD(VSSetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(VSSetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(Begin)(This,pAsync)	\
STDMETHOD(End)(This,pAsync)	\
STDMETHOD(GetData)(This,pAsync,pData,DataSize,GetDataFlags)	\
STDMETHOD(SetPredication)(This,pPredicate,PredicateValue)	\
STDMETHOD(GSSetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(GSSetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(OMSetRenderTargets)(This,NumViews,ppRenderTargetViews,pDepthStencilView)	\
STDMETHOD(OMSetRenderTargetsAndUnorderedAccessViews)(This,NumRTVs,ppRenderTargetViews,pDepthStencilView,UAVStartSlot,NumUAVs,ppUnorderedAccessViews,pUAVInitialCounts)	\
STDMETHOD(OMSetBlendState)(This,pBlendState,BlendFactor,SampleMask)	\
STDMETHOD(OMSetDepthStencilState)(This,pDepthStencilState,StencilRef)	\
STDMETHOD(SOSetTargets)(This,NumBuffers,ppSOTargets,pOffsets)	\
STDMETHOD(DrawAuto)(This)	\
STDMETHOD(DrawIndexedInstancedIndirect)(This,pBufferForArgs,AlignedByteOffsetForArgs)	\
STDMETHOD(DrawInstancedIndirect)(This,pBufferForArgs,AlignedByteOffsetForArgs)	\
STDMETHOD(Dispatch)(This,ThreadGroupCountX,ThreadGroupCountY,ThreadGroupCountZ)	\
STDMETHOD(DispatchIndirect)(This,pBufferForArgs,AlignedByteOffsetForArgs)	\
STDMETHOD(RSSetState)(This,pRasterizerState)	\
STDMETHOD(RSSetViewports)(This,NumViewports,pViewports)	\
STDMETHOD(RSSetScissorRects)(This,NumRects,pRects)	\
STDMETHOD(CopySubresourceRegion)(This,pDstResource,DstSubresource,DstX,DstY,DstZ,pSrcResource,SrcSubresource,pSrcBox)	\
STDMETHOD(CopyResource)(This,pDstResource,pSrcResource)	\
STDMETHOD(UpdateSubresource)(This,pDstResource,DstSubresource,pDstBox,pSrcData,SrcRowPitch,SrcDepthPitch)	\
STDMETHOD(CopyStructureCount)(This,pDstBuffer,DstAlignedByteOffset,pSrcView)	\
STDMETHOD(ClearRenderTargetView)(This,pRenderTargetView,ColorRGBA)	\
STDMETHOD(ClearUnorderedAccessViewUint)(This,pUnorderedAccessView,Values)	\
STDMETHOD(ClearUnorderedAccessViewFloat)(This,pUnorderedAccessView,Values)	\
STDMETHOD(ClearDepthStencilView)(This,pDepthStencilView,ClearFlags,Depth,Stencil)	\
STDMETHOD(GenerateMips)(This,pShaderResourceView)	\
STDMETHOD(SetResourceMinLOD)(This,pResource,MinLOD)	\
STDMETHOD(GetResourceMinLOD)(This,pResource)	\
STDMETHOD(ResolveSubresource)(This,pDstResource,DstSubresource,pSrcResource,SrcSubresource,Format)	\
STDMETHOD(ExecuteCommandList)(This,pCommandList,RestoreContextState)	\
STDMETHOD(HSSetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(HSSetShader)(This,pHullShader,ppClassInstances,NumClassInstances)	\
STDMETHOD(HSSetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(HSSetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(DSSetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(DSSetShader)(This,pDomainShader,ppClassInstances,NumClassInstances)	\
STDMETHOD(DSSetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(DSSetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(CSSetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(CSSetUnorderedAccessViews)(This,StartSlot,NumUAVs,ppUnorderedAccessViews,pUAVInitialCounts)	\
STDMETHOD(CSSetShader)(This,pComputeShader,ppClassInstances,NumClassInstances)	\
STDMETHOD(CSSetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(CSSetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(VSGetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(PSGetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(PSGetShader)(This,ppPixelShader,ppClassInstances,pNumClassInstances)	\
STDMETHOD(PSGetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(VSGetShader)(This,ppVertexShader,ppClassInstances,pNumClassInstances)	\
STDMETHOD(PSGetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(IAGetInputLayout)(This,ppInputLayout)	\
STDMETHOD(IAGetVertexBuffers)(This,StartSlot,NumBuffers,ppVertexBuffers,pStrides,pOffsets)	\
STDMETHOD(IAGetIndexBuffer)(This,pIndexBuffer,Format,Offset)	\
STDMETHOD(GSGetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(GSGetShader)(This,ppGeometryShader,ppClassInstances,pNumClassInstances)	\
STDMETHOD(IAGetPrimitiveTopology)(This,pTopology)	\
STDMETHOD(VSGetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(VSGetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(GetPredication)(This,ppPredicate,pPredicateValue)	\
STDMETHOD(GSGetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(GSGetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(OMGetRenderTargets)(This,NumViews,ppRenderTargetViews,ppDepthStencilView)	\
STDMETHOD(OMGetRenderTargetsAndUnorderedAccessViews)(This,NumRTVs,ppRenderTargetViews,ppDepthStencilView,UAVStartSlot,NumUAVs,ppUnorderedAccessViews)	\
STDMETHOD(OMGetBlendState)(This,ppBlendState,BlendFactor,pSampleMask)	\
STDMETHOD(OMGetDepthStencilState)(This,ppDepthStencilState,pStencilRef)	\
STDMETHOD(SOGetTargets)(This,NumBuffers,ppSOTargets)	\
STDMETHOD(RSGetState)(This,ppRasterizerState)	\
STDMETHOD(RSGetViewports)(This,pNumViewports,pViewports)	\
STDMETHOD(RSGetScissorRects)(This,pNumRects,pRects)	\
STDMETHOD(HSGetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(HSGetShader)(This,ppHullShader,ppClassInstances,pNumClassInstances)	\
STDMETHOD(HSGetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(HSGetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(DSGetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(DSGetShader)(This,ppDomainShader,ppClassInstances,pNumClassInstances)	\
STDMETHOD(DSGetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(DSGetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(CSGetShaderResources)(This,StartSlot,NumViews,ppShaderResourceViews)	\
STDMETHOD(CSGetUnorderedAccessViews)(This,StartSlot,NumUAVs,ppUnorderedAccessViews)	\
STDMETHOD(CSGetShader)(This,ppComputeShader,ppClassInstances,pNumClassInstances)	\
STDMETHOD(CSGetSamplers)(This,StartSlot,NumSamplers,ppSamplers)	\
STDMETHOD(CSGetConstantBuffers)(This,StartSlot,NumBuffers,ppConstantBuffers)	\
STDMETHOD(ClearState)(This)	\
STDMETHOD(Flush)(This)	\
STDMETHOD(GetType)(This)	\
STDMETHOD(GetContextFlags)(This)	\
STDMETHOD(FinishCommandList)(This,RestoreDeferredContextState,ppCommandList)	\
STDMETHOD(CopySubresourceRegion1)(This,pDstResource,DstSubresource,DstX,DstY,DstZ,pSrcResource,SrcSubresource,pSrcBox,CopyFlags)	\
STDMETHOD(UpdateSubresource1)(This,pDstResource,DstSubresource,pDstBox,pSrcData,SrcRowPitch,SrcDepthPitch,CopyFlags)	\
STDMETHOD(DiscardResource)(This,pResource)	\
STDMETHOD(DiscardView)(This,pResourceView)	\
STDMETHOD(VSSetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(HSSetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(DSSetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(GSSetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(PSSetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(CSSetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(VSGetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(HSGetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(DSGetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(GSGetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(PSGetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(CSGetConstantBuffers1)(This,StartSlot,NumBuffers,ppConstantBuffers,pFirstConstant,pNumConstants)	\
STDMETHOD(SwapDeviceContextState)(This,pState,ppPreviousState)	\
STDMETHOD(ClearView)(This,pView,Color,pRect,NumRects)	\
STDMETHOD(DiscardView1)(This,pResourceView,pRects,NumRects)	\
"
)

D3D11_1.ID3D11RasterizerState1 := {}
D3D11_1.ID3D11RasterizerState1.name := "ID3D11RasterizerState1"
D3D11_1.ID3D11RasterizerState1.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(GetDevice)(This,ppDevice)	\
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)	\
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)	\
STDMETHOD(GetDesc)(This,pDesc)	\
STDMETHOD(GetDesc1)(This,pDesc)	\
"
)

D3D11_1.ID3D11VideoContext1 := {}
D3D11_1.ID3D11VideoContext1.name := "ID3D11VideoContext1"
D3D11_1.ID3D11VideoContext1.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(GetDevice)(This,ppDevice)	\
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)	\
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)	\
STDMETHOD(GetDecoderBuffer)(This,pDecoder,Type,pBufferSize,ppBuffer)	\
STDMETHOD(ReleaseDecoderBuffer)(This,pDecoder,Type)	\
STDMETHOD(DecoderBeginFrame)(This,pDecoder,pView,ContentKeySize,pContentKey)	\
STDMETHOD(DecoderEndFrame)(This,pDecoder)	\
STDMETHOD(SubmitDecoderBuffers)(This,pDecoder,NumBuffers,pBufferDesc)	\
STDMETHOD(DecoderExtension)(This,pDecoder,pExtensionData)	\
STDMETHOD(VideoProcessorSetOutputTargetRect)(This,pVideoProcessor,Enable,pRect)	\
STDMETHOD(VideoProcessorSetOutputBackgroundColor)(This,pVideoProcessor,YCbCr,pColor)	\
STDMETHOD(VideoProcessorSetOutputColorSpace)(This,pVideoProcessor,pColorSpace)	\
STDMETHOD(VideoProcessorSetOutputAlphaFillMode)(This,pVideoProcessor,AlphaFillMode,StreamIndex)	\
STDMETHOD(VideoProcessorSetOutputConstriction)(This,pVideoProcessor,Enable,Size)	\
STDMETHOD(VideoProcessorSetOutputStereoMode)(This,pVideoProcessor,Enable)	\
STDMETHOD(VideoProcessorSetOutputExtension)(This,pVideoProcessor,pExtensionGuid,DataSize,pData)	\
STDMETHOD(VideoProcessorGetOutputTargetRect)(This,pVideoProcessor,Enabled,pRect)	\
STDMETHOD(VideoProcessorGetOutputBackgroundColor)(This,pVideoProcessor,pYCbCr,pColor)	\
STDMETHOD(VideoProcessorGetOutputColorSpace)(This,pVideoProcessor,pColorSpace)	\
STDMETHOD(VideoProcessorGetOutputAlphaFillMode)(This,pVideoProcessor,pAlphaFillMode,pStreamIndex)	\
STDMETHOD(VideoProcessorGetOutputConstriction)(This,pVideoProcessor,pEnabled,pSize)	\
STDMETHOD(VideoProcessorGetOutputStereoMode)(This,pVideoProcessor,pEnabled)	\
STDMETHOD(VideoProcessorGetOutputExtension)(This,pVideoProcessor,pExtensionGuid,DataSize,pData)	\
STDMETHOD(VideoProcessorSetStreamFrameFormat)(This,pVideoProcessor,StreamIndex,FrameFormat)	\
STDMETHOD(VideoProcessorSetStreamColorSpace)(This,pVideoProcessor,StreamIndex,pColorSpace)	\
STDMETHOD(VideoProcessorSetStreamOutputRate)(This,pVideoProcessor,StreamIndex,OutputRate,RepeatFrame,pCustomRate)	\
STDMETHOD(VideoProcessorSetStreamSourceRect)(This,pVideoProcessor,StreamIndex,Enable,pRect)	\
STDMETHOD(VideoProcessorSetStreamDestRect)(This,pVideoProcessor,StreamIndex,Enable,pRect)	\
STDMETHOD(VideoProcessorSetStreamAlpha)(This,pVideoProcessor,StreamIndex,Enable,Alpha)	\
STDMETHOD(VideoProcessorSetStreamPalette)(This,pVideoProcessor,StreamIndex,Count,pEntries)	\
STDMETHOD(VideoProcessorSetStreamPixelAspectRatio)(This,pVideoProcessor,StreamIndex,Enable,pSourceAspectRatio,pDestinationAspectRatio)	\
STDMETHOD(VideoProcessorSetStreamLumaKey)(This,pVideoProcessor,StreamIndex,Enable,Lower,Upper)	\
STDMETHOD(VideoProcessorSetStreamStereoFormat)(This,pVideoProcessor,StreamIndex,Enable,Format,LeftViewFrame0,BaseViewFrame0,FlipMode,MonoOffset)	\
STDMETHOD(VideoProcessorSetStreamAutoProcessingMode)(This,pVideoProcessor,StreamIndex,Enable)	\
STDMETHOD(VideoProcessorSetStreamFilter)(This,pVideoProcessor,StreamIndex,Filter,Enable,Level)	\
STDMETHOD(VideoProcessorSetStreamExtension)(This,pVideoProcessor,StreamIndex,pExtensionGuid,DataSize,pData)	\
STDMETHOD(VideoProcessorGetStreamFrameFormat)(This,pVideoProcessor,StreamIndex,pFrameFormat)	\
STDMETHOD(VideoProcessorGetStreamColorSpace)(This,pVideoProcessor,StreamIndex,pColorSpace)	\
STDMETHOD(VideoProcessorGetStreamOutputRate)(This,pVideoProcessor,StreamIndex,pOutputRate,pRepeatFrame,pCustomRate)	\
STDMETHOD(VideoProcessorGetStreamSourceRect)(This,pVideoProcessor,StreamIndex,pEnabled,pRect)	\
STDMETHOD(VideoProcessorGetStreamDestRect)(This,pVideoProcessor,StreamIndex,pEnabled,pRect)	\
STDMETHOD(VideoProcessorGetStreamAlpha)(This,pVideoProcessor,StreamIndex,pEnabled,pAlpha)	\
STDMETHOD(VideoProcessorGetStreamPalette)(This,pVideoProcessor,StreamIndex,Count,pEntries)	\
STDMETHOD(VideoProcessorGetStreamPixelAspectRatio)(This,pVideoProcessor,StreamIndex,pEnabled,pSourceAspectRatio,pDestinationAspectRatio)	\
STDMETHOD(VideoProcessorGetStreamLumaKey)(This,pVideoProcessor,StreamIndex,pEnabled,pLower,pUpper)	\
STDMETHOD(VideoProcessorGetStreamStereoFormat)(This,pVideoProcessor,StreamIndex,pEnable,pFormat,pLeftViewFrame0,pBaseViewFrame0,pFlipMode,MonoOffset)	\
STDMETHOD(VideoProcessorGetStreamAutoProcessingMode)(This,pVideoProcessor,StreamIndex,pEnabled)	\
STDMETHOD(VideoProcessorGetStreamFilter)(This,pVideoProcessor,StreamIndex,Filter,pEnabled,pLevel)	\
STDMETHOD(VideoProcessorGetStreamExtension)(This,pVideoProcessor,StreamIndex,pExtensionGuid,DataSize,pData)	\
STDMETHOD(VideoProcessorBlt)(This,pVideoProcessor,pView,OutputFrame,StreamCount,pStreams)	\
STDMETHOD(NegotiateCryptoSessionKeyExchange)(This,pCryptoSession,DataSize,pData)	\
STDMETHOD(EncryptionBlt)(This,pCryptoSession,pSrcSurface,pDstSurface,IVSize,pIV)	\
STDMETHOD(DecryptionBlt)(This,pCryptoSession,pSrcSurface,pDstSurface,pEncryptedBlockInfo,ContentKeySize,pContentKey,IVSize,pIV)	\
STDMETHOD(StartSessionKeyRefresh)(This,pCryptoSession,RandomNumberSize,pRandomNumber)	\
STDMETHOD(FinishSessionKeyRefresh)(This,pCryptoSession)	\
STDMETHOD(GetEncryptionBltKey)(This,pCryptoSession,KeySize,pReadbackKey)	\
STDMETHOD(NegotiateAuthenticatedChannelKeyExchange)(This,pChannel,DataSize,pData)	\
STDMETHOD(QueryAuthenticatedChannel)(This,pChannel,InputSize,pInput,OutputSize,pOutput)	\
STDMETHOD(ConfigureAuthenticatedChannel)(This,pChannel,InputSize,pInput,pOutput)	\
STDMETHOD(VideoProcessorSetStreamRotation)(This,pVideoProcessor,StreamIndex,Enable,Rotation)	\
STDMETHOD(VideoProcessorGetStreamRotation)(This,pVideoProcessor,StreamIndex,pEnable,pRotation)	\
STDMETHOD(SubmitDecoderBuffers1)(This,pDecoder,NumBuffers,pBufferDesc)	\
STDMETHOD(GetDataForNewHardwareKey)(This,pCryptoSession,PrivateInputSize,pPrivatInputData,pPrivateOutputData)	\
STDMETHOD(CheckCryptoSessionStatus)(This,pCryptoSession,pStatus)	\
STDMETHOD(DecoderEnableDownsampling)(This,pDecoder,InputColorSpace,pOutputDesc,ReferenceFrameCount)	\
STDMETHOD(DecoderUpdateDownsampling)(This,pDecoder,pOutputDesc)	\
STDMETHOD(VideoProcessorSetOutputColorSpace1)(This,pVideoProcessor,ColorSpace)	\
STDMETHOD(VideoProcessorSetOutputShaderUsage)(This,pVideoProcessor,ShaderUsage)	\
STDMETHOD(VideoProcessorGetOutputColorSpace1)(This,pVideoProcessor,pColorSpace)	\
STDMETHOD(VideoProcessorGetOutputShaderUsage)(This,pVideoProcessor,pShaderUsage)	\
STDMETHOD(VideoProcessorSetStreamColorSpace1)(This,pVideoProcessor,StreamIndex,ColorSpace)	\
STDMETHOD(VideoProcessorSetStreamMirror)(This,pVideoProcessor,StreamIndex,Enable,FlipHorizontal,FlipVertical)	\
STDMETHOD(VideoProcessorGetStreamColorSpace1)(This,pVideoProcessor,StreamIndex,pColorSpace)	\
STDMETHOD(VideoProcessorGetStreamMirror)(This,pVideoProcessor,StreamIndex,pEnable,pFlipHorizontal,pFlipVertical)	\
STDMETHOD(VideoProcessorGetBehaviorHints)(This,pVideoProcessor,OutputWidth,OutputHeight,OutputFormat,StreamCount,pStreams,pBehaviorHints)	\
"
)

D3D11_1.ID3D11VideoDevice1 := {}
D3D11_1.ID3D11VideoDevice1.name := "ID3D11VideoDevice1"
D3D11_1.ID3D11VideoDevice1.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(CreateVideoDecoder)(This,pVideoDesc,pConfig,ppDecoder)	\
STDMETHOD(CreateVideoProcessor)(This,pEnum,RateConversionIndex,ppVideoProcessor)	\
STDMETHOD(CreateAuthenticatedChannel)(This,ChannelType,ppAuthenticatedChannel)	\
STDMETHOD(CreateCryptoSession)(This,pCryptoType,pDecoderProfile,pKeyExchangeType,ppCryptoSession)	\
STDMETHOD(CreateVideoDecoderOutputView)(This,pResource,pDesc,ppVDOVView)	\
STDMETHOD(CreateVideoProcessorInputView)(This,pResource,pEnum,pDesc,ppVPIView)	\
STDMETHOD(CreateVideoProcessorOutputView)(This,pResource,pEnum,pDesc,ppVPOView)	\
STDMETHOD(CreateVideoProcessorEnumerator)(This,pDesc,ppEnum)	\
STDMETHOD(GetVideoDecoderProfileCount)(This)	\
STDMETHOD(GetVideoDecoderProfile)(This,Index,pDecoderProfile)	\
STDMETHOD(CheckVideoDecoderFormat)(This,pDecoderProfile,Format,pSupported)	\
STDMETHOD(GetVideoDecoderConfigCount)(This,pDesc,pCount)	\
STDMETHOD(GetVideoDecoderConfig)(This,pDesc,Index,pConfig)	\
STDMETHOD(GetContentProtectionCaps)(This,pCryptoType,pDecoderProfile,pCaps)	\
STDMETHOD(CheckCryptoKeyExchange)(This,pCryptoType,pDecoderProfile,Index,pKeyExchangeType)	\
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)	\
STDMETHOD(GetCryptoSessionPrivateDataSize)(This,pCryptoType,pDecoderProfile,pKeyExchangeType,pPrivateInputSize,pPrivateOutputSize)	\
STDMETHOD(GetVideoDecoderCaps)(This,pDecoderProfile,SampleWidth,SampleHeight,pFrameRate,BitRate,pCryptoType,pDecoderCaps)	\
STDMETHOD(CheckVideoDecoderDownsampling)(This,pInputDesc,InputColorSpace,pInputConfig,pFrameRate,pOutputDesc,pSupported,pRealTimeHint)	\
STDMETHOD(RecommendVideoDecoderDownsampleParameters)(This,pInputDesc,InputColorSpace,pInputConfig,pFrameRate,pRecommendedOutputDesc)	\
"
)

D3D11_1.ID3D11VideoProcessorEnumerator1 := {}
D3D11_1.ID3D11VideoProcessorEnumerator1.name := "ID3D11VideoProcessorEnumerator1"
D3D11_1.ID3D11VideoProcessorEnumerator1.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(GetDevice)(This,ppDevice)	\
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)	\
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)	\
STDMETHOD(GetVideoProcessorContentDesc)(This,pContentDesc)	\
STDMETHOD(CheckVideoProcessorFormat)(This,Format,pFlags)	\
STDMETHOD(GetVideoProcessorCaps)(This,pCaps)	\
STDMETHOD(GetVideoProcessorRateConversionCaps)(This,TypeIndex,pCaps)	\
STDMETHOD(GetVideoProcessorCustomRate)(This,TypeIndex,CustomRateIndex,pRate)	\
STDMETHOD(GetVideoProcessorFilterRange)(This,Filter,pRange)	\
STDMETHOD(CheckVideoProcessorFormatConversion)(This,InputFormat,InputColorSpace,OutputFormat,OutputColorSpace,pSupported)	\
"
)

D3D11_1.ID3DDeviceContextState := {}
D3D11_1.ID3DDeviceContextState.name := "ID3DDeviceContextState"
D3D11_1.ID3DDeviceContextState.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(GetDevice)(This,ppDevice)	\
STDMETHOD(GetPrivateData)(This,guid,pDataSize,pData)	\
STDMETHOD(SetPrivateData)(This,guid,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,guid,pData)	\
"
)

D3D11_1.ID3DUserDefinedAnnotation := {}
D3D11_1.ID3DUserDefinedAnnotation.name := "ID3DUserDefinedAnnotation"
D3D11_1.ID3DUserDefinedAnnotation.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(BeginEvent)(This,Name)	\
STDMETHOD(EndEvent)(This)	\
STDMETHOD(SetMarker)(This,Name)	\
STDMETHOD(GetStatus)(This)	\
"
)



Global D3D11_LOGIC_OP_SET := ( D3D11_LOGIC_OP_CLEAR + 1 )
Global D3D11_LOGIC_OP_COPY := ( D3D11_LOGIC_OP_SET + 1 )
Global D3D11_LOGIC_OP_COPY_INVERTED := ( D3D11_LOGIC_OP_COPY + 1 )
Global D3D11_LOGIC_OP_NOOP := ( D3D11_LOGIC_OP_COPY_INVERTED + 1 )
Global D3D11_LOGIC_OP_INVERT := ( D3D11_LOGIC_OP_NOOP + 1 )
Global D3D11_LOGIC_OP_AND := ( D3D11_LOGIC_OP_INVERT + 1 )
Global D3D11_LOGIC_OP_NAND := ( D3D11_LOGIC_OP_AND + 1 )
Global D3D11_LOGIC_OP_OR := ( D3D11_LOGIC_OP_NAND + 1 )
Global D3D11_LOGIC_OP_NOR := ( D3D11_LOGIC_OP_OR + 1 )
Global D3D11_LOGIC_OP_XOR := ( D3D11_LOGIC_OP_NOR + 1 )
Global D3D11_LOGIC_OP_EQUIV := ( D3D11_LOGIC_OP_XOR + 1 )
Global D3D11_LOGIC_OP_AND_REVERSE := ( D3D11_LOGIC_OP_EQUIV + 1 )
Global D3D11_LOGIC_OP_AND_INVERTED := ( D3D11_LOGIC_OP_AND_REVERSE + 1 )
Global D3D11_LOGIC_OP_OR_REVERSE := ( D3D11_LOGIC_OP_AND_INVERTED + 1 )
Global D3D11_LOGIC_OP_OR_INVERTED := ( D3D11_LOGIC_OP_OR_REVERSE + 1 )
Global D3D11_1_CREATE_DEVICE_CONTEXT_STATE_SINGLETHREADED := 0x1
Global D3D11_VIDEO_DECODER_CAPS_DOWNSAMPLE := 0x1
Global D3D11_VIDEO_DECODER_CAPS_NON_REAL_TIME := 0x2
Global D3D11_VIDEO_DECODER_CAPS_DOWNSAMPLE_DYNAMIC := 0x4
Global D3D11_VIDEO_DECODER_CAPS_DOWNSAMPLE_REQUIRED := 0x8
Global D3D11_VIDEO_DECODER_CAPS_UNSUPPORTED := 0x10
Global D3D11_VIDEO_PROCESSOR_BEHAVIOR_HINT_MULTIPLANE_OVERLAY_ROTATION := 0x1
Global D3D11_VIDEO_PROCESSOR_BEHAVIOR_HINT_MULTIPLANE_OVERLAY_RESIZE := 0x2
Global D3D11_VIDEO_PROCESSOR_BEHAVIOR_HINT_MULTIPLANE_OVERLAY_COLOR_SPACE_CONVERSION := 0x4
Global D3D11_VIDEO_PROCESSOR_BEHAVIOR_HINT_TRIPLE_BUFFER_OUTPUT := 0x8
Global D3D11_CRYPTO_SESSION_STATUS_KEY_LOST := 1
Global D3D11_CRYPTO_SESSION_STATUS_KEY_AND_CONTENT_LOST := 2

D3D11_1.err := {}

