;File automatically generated by CrappyCppHeaderParser.ahk (Copyright@ peixoto)

Global d3DCommon := {}
d3DCommon.IID_ID3D10Blob := "{8ba5fb08-5195-40e2-ac58-0d989c3a0102}"
d3DCommon.WKPDID_D3DDebugObjectName := "{429b8c22-9188-4b0c-8742-acb0bf85c200}"

d3DCommon.ID3D10Blob:= {}
d3DCommon.ID3D10Blob.name := "ID3D10Blob"
d3DCommon.ID3D10Blob.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(GetBufferPointer)(This)
STDMETHOD(GetBufferSize)(This)
"
)




d3DCommon.err := {}

