;File automatically generated by CrappyCppHeaderParser.ahk (Copyright@ peixoto)

Global DXGI := {}
DXGI.IID_IDXGIObject := "{aec22fb8-76f3-4639-9be0-28eb43a67a2e}"
DXGI.IID_IDXGIDeviceSubObject := "{3d3e0379-f9de-4d58-bb6c-18d62992f1a6}"
DXGI.IID_IDXGIResource := "{035f3ab4-482e-4e50-b41f-8a7f8bd8960b}"
DXGI.IID_IDXGIKeyedMutex := "{9d8e1289-d7b3-465f-8126-250e349af85d}"
DXGI.IID_IDXGISurface := "{cafcb56c-6ac3-4889-bf47-9e23bbd260ec}"
DXGI.IID_IDXGISurface1 := "{4AE63092-6327-4c1b-80AE-BFE12EA32B86}"
DXGI.IID_IDXGIAdapter := "{2411e7e1-12ac-4ccf-bd14-9798e8534dc0}"
DXGI.IID_IDXGIOutput := "{ae02eedb-c735-4690-8d52-5a8dc20213aa}"
DXGI.IID_IDXGISwapChain := "{310d36a0-d2e7-4c0a-aa04-6a9d23b8886a}"
DXGI.IID_IDXGIFactory := "{7b7166ec-21c7-44ae-b21a-c9ae321ae369}"
DXGI.IID_IDXGIDevice := "{54ec77fa-1377-44e6-8c32-88fd5f44c84c}"
DXGI.IID_IDXGIFactory1 := "{770aae78-f26f-4dba-a829-253c83d1b387}"
DXGI.IID_IDXGIAdapter1 := "{29038f61-3839-4626-91fd-086879011a05}"
DXGI.IID_IDXGIDevice1 := "{77db970f-6276-48ba-ba28-070143b4392c}"

DXGI.IDXGIAdapter:= {}
DXGI.IDXGIAdapter.name := "IDXGIAdapter"
DXGI.IDXGIAdapter.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(SetPrivateData)(This,Name,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,Name,pUnknown)
STDMETHOD(GetPrivateData)(This,Name,pDataSize,pData)
STDMETHOD(GetParent)(This,riid,ppParent)
STDMETHOD(EnumOutputs)(This,Output,ppOutput)
STDMETHOD(GetDesc)(This,pDesc)
STDMETHOD(CheckInterfaceSupport)(This,InterfaceName,pUMDVersion)
"
)

DXGI.IDXGIAdapter1:= {}
DXGI.IDXGIAdapter1.name := "IDXGIAdapter1"
DXGI.IDXGIAdapter1.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(SetPrivateData)(This,Name,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,Name,pUnknown)
STDMETHOD(GetPrivateData)(This,Name,pDataSize,pData)
STDMETHOD(GetParent)(This,riid,ppParent)
STDMETHOD(EnumOutputs)(This,Output,ppOutput)
STDMETHOD(GetDesc)(This,pDesc)
STDMETHOD(CheckInterfaceSupport)(This,InterfaceName,pUMDVersion)
STDMETHOD(GetDesc1)(This,pDesc)
"
)

DXGI.IDXGIDevice:= {}
DXGI.IDXGIDevice.name := "IDXGIDevice"
DXGI.IDXGIDevice.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(SetPrivateData)(This,Name,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,Name,pUnknown)
STDMETHOD(GetPrivateData)(This,Name,pDataSize,pData)
STDMETHOD(GetParent)(This,riid,ppParent)
STDMETHOD(GetAdapter)(This,pAdapter)
STDMETHOD(CreateSurface)(This,pDesc,NumSurfaces,Usage,pSharedResource,ppSurface)
STDMETHOD(QueryResourceResidency)(This,ppResources,pResidencyStatus,NumResources)
STDMETHOD(SetGPUThreadPriority)(This,Priority)
STDMETHOD(GetGPUThreadPriority)(This,pPriority)
"
)

DXGI.IDXGIDevice1:= {}
DXGI.IDXGIDevice1.name := "IDXGIDevice1"
DXGI.IDXGIDevice1.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(SetPrivateData)(This,Name,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,Name,pUnknown)
STDMETHOD(GetPrivateData)(This,Name,pDataSize,pData)
STDMETHOD(GetParent)(This,riid,ppParent)
STDMETHOD(GetAdapter)(This,pAdapter)
STDMETHOD(CreateSurface)(This,pDesc,NumSurfaces,Usage,pSharedResource,ppSurface)
STDMETHOD(QueryResourceResidency)(This,ppResources,pResidencyStatus,NumResources)
STDMETHOD(SetGPUThreadPriority)(This,Priority)
STDMETHOD(GetGPUThreadPriority)(This,pPriority)
STDMETHOD(SetMaximumFrameLatency)(This,MaxLatency)
STDMETHOD(GetMaximumFrameLatency)(This,pMaxLatency)
"
)

DXGI.IDXGIDeviceSubObject:= {}
DXGI.IDXGIDeviceSubObject.name := "IDXGIDeviceSubObject"
DXGI.IDXGIDeviceSubObject.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(SetPrivateData)(This,Name,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,Name,pUnknown)
STDMETHOD(GetPrivateData)(This,Name,pDataSize,pData)
STDMETHOD(GetParent)(This,riid,ppParent)
STDMETHOD(GetDevice)(This,riid,ppDevice)
"
)

DXGI.IDXGIFactory:= {}
DXGI.IDXGIFactory.name := "IDXGIFactory"
DXGI.IDXGIFactory.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(SetPrivateData)(This,Name,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,Name,pUnknown)
STDMETHOD(GetPrivateData)(This,Name,pDataSize,pData)
STDMETHOD(GetParent)(This,riid,ppParent)
STDMETHOD(EnumAdapters)(This,Adapter,ppAdapter)
STDMETHOD(MakeWindowAssociation)(This,WindowHandle,Flags)
STDMETHOD(GetWindowAssociation)(This,pWindowHandle)
STDMETHOD(CreateSwapChain)(This,pDevice,pDesc,ppSwapChain)
STDMETHOD(CreateSoftwareAdapter)(This,Module,ppAdapter)
"
)

DXGI.IDXGIFactory1:= {}
DXGI.IDXGIFactory1.name := "IDXGIFactory1"
DXGI.IDXGIFactory1.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(SetPrivateData)(This,Name,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,Name,pUnknown)
STDMETHOD(GetPrivateData)(This,Name,pDataSize,pData)
STDMETHOD(GetParent)(This,riid,ppParent)
STDMETHOD(EnumAdapters)(This,Adapter,ppAdapter)
STDMETHOD(MakeWindowAssociation)(This,WindowHandle,Flags)
STDMETHOD(GetWindowAssociation)(This,pWindowHandle)
STDMETHOD(CreateSwapChain)(This,pDevice,pDesc,ppSwapChain)
STDMETHOD(CreateSoftwareAdapter)(This,Module,ppAdapter)
STDMETHOD(EnumAdapters1)(This,Adapter,ppAdapter)
STDMETHOD(IsCurrent)(This)
"
)

DXGI.IDXGIKeyedMutex:= {}
DXGI.IDXGIKeyedMutex.name := "IDXGIKeyedMutex"
DXGI.IDXGIKeyedMutex.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(SetPrivateData)(This,Name,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,Name,pUnknown)
STDMETHOD(GetPrivateData)(This,Name,pDataSize,pData)
STDMETHOD(GetParent)(This,riid,ppParent)
STDMETHOD(GetDevice)(This,riid,ppDevice)
STDMETHOD(AcquireSync)(This,Key,dwMilliseconds)
STDMETHOD(ReleaseSync)(This,Key)
"
)

DXGI.IDXGIObject:= {}
DXGI.IDXGIObject.name := "IDXGIObject"
DXGI.IDXGIObject.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(SetPrivateData)(This,Name,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,Name,pUnknown)
STDMETHOD(GetPrivateData)(This,Name,pDataSize,pData)
STDMETHOD(GetParent)(This,riid,ppParent)
"
)

DXGI.IDXGIOutput:= {}
DXGI.IDXGIOutput.name := "IDXGIOutput"
DXGI.IDXGIOutput.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(SetPrivateData)(This,Name,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,Name,pUnknown)
STDMETHOD(GetPrivateData)(This,Name,pDataSize,pData)
STDMETHOD(GetParent)(This,riid,ppParent)
STDMETHOD(GetDesc)(This,pDesc)
STDMETHOD(GetDisplayModeList)(This,EnumFormat,Flags,pNumModes,pDesc)
STDMETHOD(FindClosestMatchingMode)(This,pModeToMatch,pClosestMatch,pConcernedDevice)
STDMETHOD(WaitForVBlank)(This)
STDMETHOD(TakeOwnership)(This,pDevice,Exclusive)
STDMETHOD(ReleaseOwnership)(This)
STDMETHOD(GetGammaControlCapabilities)(This,pGammaCaps)
STDMETHOD(SetGammaControl)(This,pArray)
STDMETHOD(GetGammaControl)(This,pArray)
STDMETHOD(SetDisplaySurface)(This,pScanoutSurface)
STDMETHOD(GetDisplaySurfaceData)(This,pDestination)
STDMETHOD(GetFrameStatistics)(This,pStats)
"
)

DXGI.IDXGIResource:= {}
DXGI.IDXGIResource.name := "IDXGIResource"
DXGI.IDXGIResource.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(SetPrivateData)(This,Name,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,Name,pUnknown)
STDMETHOD(GetPrivateData)(This,Name,pDataSize,pData)
STDMETHOD(GetParent)(This,riid,ppParent)
STDMETHOD(GetDevice)(This,riid,ppDevice)
STDMETHOD(GetSharedHandle)(This,pSharedHandle)
STDMETHOD(GetUsage)(This,pUsage)
STDMETHOD(SetEvictionPriority)(This,EvictionPriority)
STDMETHOD(GetEvictionPriority)(This,pEvictionPriority)
"
)

DXGI.IDXGISurface:= {}
DXGI.IDXGISurface.name := "IDXGISurface"
DXGI.IDXGISurface.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(SetPrivateData)(This,Name,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,Name,pUnknown)
STDMETHOD(GetPrivateData)(This,Name,pDataSize,pData)
STDMETHOD(GetParent)(This,riid,ppParent)
STDMETHOD(GetDevice)(This,riid,ppDevice)
STDMETHOD(GetDesc)(This,pDesc)
STDMETHOD(Map)(This,pLockedRect,MapFlags)
STDMETHOD(Unmap)(This)
"
)

DXGI.IDXGISurface1:= {}
DXGI.IDXGISurface1.name := "IDXGISurface1"
DXGI.IDXGISurface1.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(SetPrivateData)(This,Name,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,Name,pUnknown)
STDMETHOD(GetPrivateData)(This,Name,pDataSize,pData)
STDMETHOD(GetParent)(This,riid,ppParent)
STDMETHOD(GetDevice)(This,riid,ppDevice)
STDMETHOD(GetDesc)(This,pDesc)
STDMETHOD(Map)(This,pLockedRect,MapFlags)
STDMETHOD(Unmap)(This)
STDMETHOD(GetDC)(This,Discard,phdc)
STDMETHOD(ReleaseDC)(This,pDirtyRect)
"
)

DXGI.IDXGISwapChain:= {}
DXGI.IDXGISwapChain.name := "IDXGISwapChain"
DXGI.IDXGISwapChain.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)
STDMETHOD(AddRef)(This)
STDMETHOD(Release)(This)
STDMETHOD(SetPrivateData)(This,Name,DataSize,pData)
STDMETHOD(SetPrivateDataInterface)(This,Name,pUnknown)
STDMETHOD(GetPrivateData)(This,Name,pDataSize,pData)
STDMETHOD(GetParent)(This,riid,ppParent)
STDMETHOD(GetDevice)(This,riid,ppDevice)
STDMETHOD(Present)(This,SyncInterval,Flags)
STDMETHOD(GetBuffer)(This,Buffer,riid,ppSurface)
STDMETHOD(SetFullscreenState)(This,Fullscreen,pTarget)
STDMETHOD(GetFullscreenState)(This,pFullscreen,ppTarget)
STDMETHOD(GetDesc)(This,pDesc)
STDMETHOD(ResizeBuffers)(This,BufferCount,Width,Height,NewFormat,SwapChainFlags)
STDMETHOD(ResizeTarget)(This,pNewTargetParameters)
STDMETHOD(GetContainingOutput)(This,ppOutput)
STDMETHOD(GetFrameStatistics)(This,pStats)
STDMETHOD(GetLastPresentCount)(This,pLastPresentCount)
"
)



Global DXGI_RESOURCE_PRIORITY_HIGH := 2684354560
Global DXGI_RESOURCE_PRIORITY_LOW := 1342177280
Global DXGI_RESOURCE_PRIORITY_MAXIMUM := 3355443200
Global DXGI_RESOURCE_PRIORITY_MINIMUM := 671088640
Global DXGI_RESOURCE_PRIORITY_NORMAL := 2013265920

DXGI.err := {}


Global DXGI_RESIDENCY_FULLY_RESIDENT := 1
Global DXGI_RESIDENCY_RESIDENT_IN_SHARED_MEMORY := 2
Global DXGI_RESIDENCY_EVICTED_TO_DISK := 3
Global DXGI_SWAP_EFFECT_DISCARD := 0
Global DXGI_SWAP_EFFECT_SEQUENTIAL := 1
Global DXGI_SWAP_CHAIN_FLAG_NONPREROTATED := 1
Global DXGI_SWAP_CHAIN_FLAG_ALLOW_MODE_SWITCH := 2
Global DXGI_SWAP_CHAIN_FLAG_GDI_COMPATIBLE := 4
Global DXGI_ADAPTER_FLAG_NONE := 0
Global DXGI_ADAPTER_FLAG_REMOTE := 1
Global DXGI_ADAPTER_FLAG_FORCE_DWORD := 0xffffffff