;File automatically generated by CrappyCppHeaderParser.ahk (Copyright@ peixoto)

Global DXGI1_6 := {}
DXGI1_6.IID_IDXGIOutput6 := "{068346e8-aaec-4b84-add7-137f513f77a1}"

DXGI1_6.IDXGIOutput6 := {}
DXGI1_6.IDXGIOutput6.name := "IDXGIOutput6"
DXGI1_6.IDXGIOutput6.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(SetPrivateData)(This,Name,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,Name,pUnknown)	\
STDMETHOD(GetPrivateData)(This,Name,pDataSize,pData)	\
STDMETHOD(GetParent)(This,riid,ppParent)	\
STDMETHOD(GetDesc)(This,pDesc)	\
STDMETHOD(GetDisplayModeList)(This,EnumFormat,Flags,pNumModes,pDesc)	\
STDMETHOD(FindClosestMatchingMode)(This,pModeToMatch,pClosestMatch,pConcernedDevice)	\
STDMETHOD(WaitForVBlank)(This)	\
STDMETHOD(TakeOwnership)(This,pDevice,Exclusive)	\
STDMETHOD(ReleaseOwnership)(This)	\
STDMETHOD(GetGammaControlCapabilities)(This,pGammaCaps)	\
STDMETHOD(SetGammaControl)(This,pArray)	\
STDMETHOD(GetGammaControl)(This,pArray)	\
STDMETHOD(SetDisplaySurface)(This,pScanoutSurface)	\
STDMETHOD(GetDisplaySurfaceData)(This,pDestination)	\
STDMETHOD(GetFrameStatistics)(This,pStats)	\
STDMETHOD(GetDisplayModeList1)(This,EnumFormat,Flags,pNumModes,pDesc)	\
STDMETHOD(FindClosestMatchingMode1)(This,pModeToMatch,pClosestMatch,pConcernedDevice)	\
STDMETHOD(GetDisplaySurfaceData1)(This,pDestination)	\
STDMETHOD(DuplicateOutput)(This,pDevice,ppOutputDuplication)	\
STDMETHOD(SupportsOverlays)(This)	\
STDMETHOD(CheckOverlaySupport)(This,EnumFormat,pConcernedDevice,pFlags)	\
STDMETHOD(CheckOverlayColorSpaceSupport)(This,Format,ColorSpace,pConcernedDevice,pFlags)	\
STDMETHOD(DuplicateOutput1)(This,pDevice,Flags,SupportedFormatsCount,pSupportedFormats,ppOutputDuplication)	\
STDMETHOD(GetDesc1)(This,pDesc)	\
STDMETHOD(CheckHardwareCompositionSupport)(This,pFlags)	\
"
)



Global DXGI_ADAPTER_FLAG3_REMOTE := 1
Global DXGI_ADAPTER_FLAG3_SOFTWARE := 2
Global DXGI_ADAPTER_FLAG3_ACG_COMPATIBLE := 4
Global DXGI_ADAPTER_FLAG3_FORCE_DWORD := 0xffffffff
Global DXGI_HARDWARE_COMPOSITION_SUPPORT_FLAG_FULLSCREEN := 1
Global DXGI_HARDWARE_COMPOSITION_SUPPORT_FLAG_WINDOWED := 2
Global DXGI_HARDWARE_COMPOSITION_SUPPORT_FLAG_CURSOR_STRETCHED := 4

DXGI1_6.err := {}

