;File automatically generated by CrappyCppHeaderParser.ahk (Copyright@ peixoto)

Global DXGI1_2 := {}
DXGI1_2.IID_IDXGIOutputDuplication := "{191cfac3-a341-470d-b26e-a864f428319c}"
DXGI1_2.IID_IDXGISurface2 := "{aba496dd-b617-4cb8-a866-bc44d7eb1fa2}"
DXGI1_2.IID_IDXGIResource1 := "{30961379-4609-4a41-998e-54fe567ee0c1}"
DXGI1_2.IID_IDXGIDevice2 := "{05008617-fbfd-4051-a790-144884b4f6a9}"
DXGI1_2.IID_IDXGISwapChain1 := "{790a45f7-0d42-4876-983a-0a55cfe6f4aa}"
DXGI1_2.IID_IDXGIFactory2 := "{50c83a1c-e072-4c48-87b0-3630fa36a6d0}"
DXGI1_2.IID_IDXGIAdapter2 := "{0AA1AE0A-FA0E-4B84-8644-E05FF8E5ACB5}"
DXGI1_2.IID_IDXGIOutput1 := "{00cddea8-939b-4b83-a340-a685226666cc}"

DXGI1_2.IDXGIAdapter2 := {}
DXGI1_2.IDXGIAdapter2.name := "IDXGIAdapter2"
DXGI1_2.IDXGIAdapter2.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(SetPrivateData)(This,Name,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,Name,pUnknown)	\
STDMETHOD(GetPrivateData)(This,Name,pDataSize,pData)	\
STDMETHOD(GetParent)(This,riid,ppParent)	\
STDMETHOD(EnumOutputs)(This,Output,ppOutput)	\
STDMETHOD(GetDesc)(This,pDesc)	\
STDMETHOD(CheckInterfaceSupport)(This,InterfaceName,pUMDVersion)	\
STDMETHOD(GetDesc1)(This,pDesc)	\
STDMETHOD(GetDesc2)(This,pDesc)	\
"
)

DXGI1_2.IDXGIDevice2 := {}
DXGI1_2.IDXGIDevice2.name := "IDXGIDevice2"
DXGI1_2.IDXGIDevice2.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(SetPrivateData)(This,Name,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,Name,pUnknown)	\
STDMETHOD(GetPrivateData)(This,Name,pDataSize,pData)	\
STDMETHOD(GetParent)(This,riid,ppParent)	\
STDMETHOD(GetAdapter)(This,pAdapter)	\
STDMETHOD(CreateSurface)(This,pDesc,NumSurfaces,Usage,pSharedResource,ppSurface)	\
STDMETHOD(QueryResourceResidency)(This,ppResources,pResidencyStatus,NumResources)	\
STDMETHOD(SetGPUThreadPriority)(This,Priority)	\
STDMETHOD(GetGPUThreadPriority)(This,pPriority)	\
STDMETHOD(SetMaximumFrameLatency)(This,MaxLatency)	\
STDMETHOD(GetMaximumFrameLatency)(This,pMaxLatency)	\
STDMETHOD(OfferResources)(This,NumResources,ppResources,Priority)	\
STDMETHOD(ReclaimResources)(This,NumResources,ppResources,pDiscarded)	\
STDMETHOD(EnqueueSetEvent)(This,hEvent)	\
"
)

DXGI1_2.IDXGIFactory2 := {}
DXGI1_2.IDXGIFactory2.name := "IDXGIFactory2"
DXGI1_2.IDXGIFactory2.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(SetPrivateData)(This,Name,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,Name,pUnknown)	\
STDMETHOD(GetPrivateData)(This,Name,pDataSize,pData)	\
STDMETHOD(GetParent)(This,riid,ppParent)	\
STDMETHOD(EnumAdapters)(This,Adapter,ppAdapter)	\
STDMETHOD(MakeWindowAssociation)(This,WindowHandle,Flags)	\
STDMETHOD(GetWindowAssociation)(This,pWindowHandle)	\
STDMETHOD(CreateSwapChain)(This,pDevice,pDesc,ppSwapChain)	\
STDMETHOD(CreateSoftwareAdapter)(This,Module,ppAdapter)	\
STDMETHOD(EnumAdapters1)(This,Adapter,ppAdapter)	\
STDMETHOD(IsCurrent)(This)	\
STDMETHOD(IsWindowedStereoEnabled)(This)	\
STDMETHOD(CreateSwapChainForHwnd)(This,pDevice,hWnd,pDesc,pFullscreenDesc,pRestrictToOutput,ppSwapChain)	\
STDMETHOD(CreateSwapChainForCoreWindow)(This,pDevice,pWindow,pDesc,pRestrictToOutput,ppSwapChain)	\
STDMETHOD(GetSharedResourceAdapterLuid)(This,hResource,pLuid)	\
STDMETHOD(RegisterStereoStatusWindow)(This,WindowHandle,wMsg,pdwCookie)	\
STDMETHOD(RegisterStereoStatusEvent)(This,hEvent,pdwCookie)	\
STDMETHOD(UnregisterStereoStatus)(This,dwCookie)	\
STDMETHOD(RegisterOcclusionStatusWindow)(This,WindowHandle,wMsg,pdwCookie)	\
STDMETHOD(RegisterOcclusionStatusEvent)(This,hEvent,pdwCookie)	\
STDMETHOD(UnregisterOcclusionStatus)(This,dwCookie)	\
STDMETHOD(CreateSwapChainForComposition)(This,pDevice,pDesc,pRestrictToOutput,ppSwapChain)	\
"
)

DXGI1_2.IDXGIOutput1 := {}
DXGI1_2.IDXGIOutput1.name := "IDXGIOutput1"
DXGI1_2.IDXGIOutput1.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(SetPrivateData)(This,Name,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,Name,pUnknown)	\
STDMETHOD(GetPrivateData)(This,Name,pDataSize,pData)	\
STDMETHOD(GetParent)(This,riid,ppParent)	\
STDMETHOD(GetDesc)(This,pDesc)	\
STDMETHOD(GetDisplayModeList)(This,EnumFormat,Flags,pNumModes,pDesc)	\
STDMETHOD(FindClosestMatchingMode)(This,pModeToMatch,pClosestMatch,pConcernedDevice)	\
STDMETHOD(WaitForVBlank)(This)	\
STDMETHOD(TakeOwnership)(This,pDevice,Exclusive)	\
STDMETHOD(ReleaseOwnership)(This)	\
STDMETHOD(GetGammaControlCapabilities)(This,pGammaCaps)	\
STDMETHOD(SetGammaControl)(This,pArray)	\
STDMETHOD(GetGammaControl)(This,pArray)	\
STDMETHOD(SetDisplaySurface)(This,pScanoutSurface)	\
STDMETHOD(GetDisplaySurfaceData)(This,pDestination)	\
STDMETHOD(GetFrameStatistics)(This,pStats)	\
STDMETHOD(GetDisplayModeList1)(This,EnumFormat,Flags,pNumModes,pDesc)	\
STDMETHOD(FindClosestMatchingMode1)(This,pModeToMatch,pClosestMatch,pConcernedDevice)	\
STDMETHOD(GetDisplaySurfaceData1)(This,pDestination)	\
STDMETHOD(DuplicateOutput)(This,pDevice,ppOutputDuplication)	\
"
)

DXGI1_2.IDXGIOutputDuplication := {}
DXGI1_2.IDXGIOutputDuplication.name := "IDXGIOutputDuplication"
DXGI1_2.IDXGIOutputDuplication.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(SetPrivateData)(This,Name,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,Name,pUnknown)	\
STDMETHOD(GetPrivateData)(This,Name,pDataSize,pData)	\
STDMETHOD(GetParent)(This,riid,ppParent)	\
STDMETHOD(GetDesc)(This,pDesc)	\
STDMETHOD(AcquireNextFrame)(This,TimeoutInMilliseconds,pFrameInfo,ppDesktopResource)	\
STDMETHOD(GetFrameDirtyRects)(This,DirtyRectsBufferSize,pDirtyRectsBuffer,pDirtyRectsBufferSizeRequired)	\
STDMETHOD(GetFrameMoveRects)(This,MoveRectsBufferSize,pMoveRectBuffer,pMoveRectsBufferSizeRequired)	\
STDMETHOD(GetFramePointerShape)(This,PointerShapeBufferSize,pPointerShapeBuffer,pPointerShapeBufferSizeRequired,pPointerShapeInfo)	\
STDMETHOD(MapDesktopSurface)(This,pLockedRect)	\
STDMETHOD(UnMapDesktopSurface)(This)	\
STDMETHOD(ReleaseFrame)(This)	\
"
)

DXGI1_2.IDXGIResource1 := {}
DXGI1_2.IDXGIResource1.name := "IDXGIResource1"
DXGI1_2.IDXGIResource1.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(SetPrivateData)(This,Name,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,Name,pUnknown)	\
STDMETHOD(GetPrivateData)(This,Name,pDataSize,pData)	\
STDMETHOD(GetParent)(This,riid,ppParent)	\
STDMETHOD(GetDevice)(This,riid,ppDevice)	\
STDMETHOD(GetSharedHandle)(This,pSharedHandle)	\
STDMETHOD(GetUsage)(This,pUsage)	\
STDMETHOD(SetEvictionPriority)(This,EvictionPriority)	\
STDMETHOD(GetEvictionPriority)(This,pEvictionPriority)	\
STDMETHOD(CreateSubresourceSurface)(This,index,ppSurface)	\
STDMETHOD(CreateSharedHandle)(This,pAttributes,dwAccess,lpName,pHandle)	\
"
)

DXGI1_2.IDXGISurface2 := {}
DXGI1_2.IDXGISurface2.name := "IDXGISurface2"
DXGI1_2.IDXGISurface2.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(SetPrivateData)(This,Name,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,Name,pUnknown)	\
STDMETHOD(GetPrivateData)(This,Name,pDataSize,pData)	\
STDMETHOD(GetParent)(This,riid,ppParent)	\
STDMETHOD(GetDevice)(This,riid,ppDevice)	\
STDMETHOD(GetDesc)(This,pDesc)	\
STDMETHOD(Map)(This,pLockedRect,MapFlags)	\
STDMETHOD(Unmap)(This)	\
STDMETHOD(GetDC)(This,Discard,phdc)	\
STDMETHOD(ReleaseDC)(This,pDirtyRect)	\
STDMETHOD(GetResource)(This,riid,ppParentResource,pSubresourceIndex)	\
"
)

DXGI1_2.IDXGISwapChain1 := {}
DXGI1_2.IDXGISwapChain1.name := "IDXGISwapChain1"
DXGI1_2.IDXGISwapChain1.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(SetPrivateData)(This,Name,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,Name,pUnknown)	\
STDMETHOD(GetPrivateData)(This,Name,pDataSize,pData)	\
STDMETHOD(GetParent)(This,riid,ppParent)	\
STDMETHOD(GetDevice)(This,riid,ppDevice)	\
STDMETHOD(Present)(This,SyncInterval,Flags)	\
STDMETHOD(GetBuffer)(This,Buffer,riid,ppSurface)	\
STDMETHOD(SetFullscreenState)(This,Fullscreen,pTarget)	\
STDMETHOD(GetFullscreenState)(This,pFullscreen,ppTarget)	\
STDMETHOD(GetDesc)(This,pDesc)	\
STDMETHOD(ResizeBuffers)(This,BufferCount,Width,Height,NewFormat,SwapChainFlags)	\
STDMETHOD(ResizeTarget)(This,pNewTargetParameters)	\
STDMETHOD(GetContainingOutput)(This,ppOutput)	\
STDMETHOD(GetFrameStatistics)(This,pStats)	\
STDMETHOD(GetLastPresentCount)(This,pLastPresentCount)	\
STDMETHOD(GetDesc1)(This,pDesc)	\
STDMETHOD(GetFullscreenDesc)(This,pDesc)	\
STDMETHOD(GetHwnd)(This,pHwnd)	\
STDMETHOD(GetCoreWindow)(This,refiid,ppUnk)	\
STDMETHOD(Present1)(This,SyncInterval,PresentFlags,pPresentParameters)	\
STDMETHOD(IsTemporaryMonoSupported)(This)	\
STDMETHOD(GetRestrictToOutput)(This,ppRestrictToOutput)	\
STDMETHOD(SetBackgroundColor)(This,pColor)	\
STDMETHOD(GetBackgroundColor)(This,pColor)	\
STDMETHOD(SetRotation)(This,Rotation)	\
STDMETHOD(GetRotation)(This,pRotation)	\
"
)



Global DXGI_SHARED_RESOURCE_WRITE := 1
Global DXGI_OUTDUPL_POINTER_SHAPE_TYPE_MONOCHROME := 0x1
Global DXGI_OUTDUPL_POINTER_SHAPE_TYPE_COLOR := 0x2
Global DXGI_OUTDUPL_POINTER_SHAPE_TYPE_MASKED_COLOR := 0x4
Global DXGI_ALPHA_MODE_PREMULTIPLIED := 1
Global DXGI_ALPHA_MODE_STRAIGHT := 2
Global DXGI_ALPHA_MODE_IGNORE := 3
Global DXGI_ALPHA_MODE_FORCE_DWORD := 0xffffffff
Global DXGI_OFFER_RESOURCE_PRIORITY_LOW := 1
Global DXGI_OFFER_RESOURCE_PRIORITY_NORMAL := ( DXGI_OFFER_RESOURCE_PRIORITY_LOW + 1 )
Global DXGI_OFFER_RESOURCE_PRIORITY_HIGH := ( DXGI_OFFER_RESOURCE_PRIORITY_NORMAL + 1 )
Global DXGI_SCALING_NONE := 1
Global DXGI_SCALING_ASPECT_RATIO_STRETCH := 2
Global DXGI_GRAPHICS_PREEMPTION_PRIMITIVE_BOUNDARY := 1
Global DXGI_GRAPHICS_PREEMPTION_TRIANGLE_BOUNDARY := 2
Global DXGI_GRAPHICS_PREEMPTION_PIXEL_BOUNDARY := 3
Global DXGI_GRAPHICS_PREEMPTION_INSTRUCTION_BOUNDARY := 4
Global DXGI_COMPUTE_PREEMPTION_DISPATCH_BOUNDARY := 1
Global DXGI_COMPUTE_PREEMPTION_THREAD_GROUP_BOUNDARY := 2
Global DXGI_COMPUTE_PREEMPTION_THREAD_BOUNDARY := 3
Global DXGI_COMPUTE_PREEMPTION_INSTRUCTION_BOUNDARY := 4

DXGI1_2.err := {}

