;File automatically generated by CrappyCppHeaderParser.ahk (Copyright@ peixoto)

Global DXGI1_3 := {}
DXGI1_3.IID_IDXGISwapChain2 := "{a8be2ac4-199f-4946-b331-79599fb98de7}"
DXGI1_3.IID_IDXGIOutput2 := "{595e39d1-2724-4663-99b1-da969de28364}"
DXGI1_3.IID_IDXGIFactory3 := "{25483823-cd46-4c7d-86ca-47aa95b837bd}"
DXGI1_3.IID_IDXGIDecodeSwapChain := "{2633066b-4514-4c7a-8fd8-12ea98059d18}"
DXGI1_3.IID_IDXGIFactoryMedia := "{41e7d1f2-a591-4f7b-a2e5-fa9c843e1c12}"
DXGI1_3.IID_IDXGISwapChainMedia := "{dd95b90b-f05f-4f6a-bd65-25bfb264bd84}"
DXGI1_3.IID_IDXGIOutput3 := "{8a6bb301-7e7e-41F4-a8e0-5b32f7f99b18}"

DXGI1_3.IDXGIDecodeSwapChain := {}
DXGI1_3.IDXGIDecodeSwapChain.name := "IDXGIDecodeSwapChain"
DXGI1_3.IDXGIDecodeSwapChain.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(PresentBuffer)(This,BufferToPresent,SyncInterval,Flags)	\
STDMETHOD(SetSourceRect)(This,pRect)	\
STDMETHOD(SetTargetRect)(This,pRect)	\
STDMETHOD(SetDestSize)(This,Width,Height)	\
STDMETHOD(GetSourceRect)(This,pRect)	\
STDMETHOD(GetTargetRect)(This,pRect)	\
STDMETHOD(GetDestSize)(This,pWidth,pHeight)	\
STDMETHOD(SetColorSpace)(This,ColorSpace)	\
STDMETHOD(GetColorSpace)(This)	\
"
)

DXGI1_3.IDXGIFactory3 := {}
DXGI1_3.IDXGIFactory3.name := "IDXGIFactory3"
DXGI1_3.IDXGIFactory3.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(SetPrivateData)(This,Name,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,Name,pUnknown)	\
STDMETHOD(GetPrivateData)(This,Name,pDataSize,pData)	\
STDMETHOD(GetParent)(This,riid,ppParent)	\
STDMETHOD(EnumAdapters)(This,Adapter,ppAdapter)	\
STDMETHOD(MakeWindowAssociation)(This,WindowHandle,Flags)	\
STDMETHOD(GetWindowAssociation)(This,pWindowHandle)	\
STDMETHOD(CreateSwapChain)(This,pDevice,pDesc,ppSwapChain)	\
STDMETHOD(CreateSoftwareAdapter)(This,Module,ppAdapter)	\
STDMETHOD(EnumAdapters1)(This,Adapter,ppAdapter)	\
STDMETHOD(IsCurrent)(This)	\
STDMETHOD(IsWindowedStereoEnabled)(This)	\
STDMETHOD(CreateSwapChainForHwnd)(This,pDevice,hWnd,pDesc,pFullscreenDesc,pRestrictToOutput,ppSwapChain)	\
STDMETHOD(CreateSwapChainForCoreWindow)(This,pDevice,pWindow,pDesc,pRestrictToOutput,ppSwapChain)	\
STDMETHOD(GetSharedResourceAdapterLuid)(This,hResource,pLuid)	\
STDMETHOD(RegisterStereoStatusWindow)(This,WindowHandle,wMsg,pdwCookie)	\
STDMETHOD(RegisterStereoStatusEvent)(This,hEvent,pdwCookie)	\
STDMETHOD(UnregisterStereoStatus)(This,dwCookie)	\
STDMETHOD(RegisterOcclusionStatusWindow)(This,WindowHandle,wMsg,pdwCookie)	\
STDMETHOD(RegisterOcclusionStatusEvent)(This,hEvent,pdwCookie)	\
STDMETHOD(UnregisterOcclusionStatus)(This,dwCookie)	\
STDMETHOD(CreateSwapChainForComposition)(This,pDevice,pDesc,pRestrictToOutput,ppSwapChain)	\
STDMETHOD(GetCreationFlags)(This)	\
"
)

DXGI1_3.IDXGIFactoryMedia := {}
DXGI1_3.IDXGIFactoryMedia.name := "IDXGIFactoryMedia"
DXGI1_3.IDXGIFactoryMedia.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(CreateSwapChainForCompositionSurfaceHandle)(This,pDevice,hSurface,pDesc,pRestrictToOutput,ppSwapChain)	\
STDMETHOD(CreateDecodeSwapChainForCompositionSurfaceHandle)(This,pDevice,hSurface,pDesc,pYuvDecodeBuffers,pRestrictToOutput,ppSwapChain)	\
"
)

DXGI1_3.IDXGIOutput2 := {}
DXGI1_3.IDXGIOutput2.name := "IDXGIOutput2"
DXGI1_3.IDXGIOutput2.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(SetPrivateData)(This,Name,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,Name,pUnknown)	\
STDMETHOD(GetPrivateData)(This,Name,pDataSize,pData)	\
STDMETHOD(GetParent)(This,riid,ppParent)	\
STDMETHOD(GetDesc)(This,pDesc)	\
STDMETHOD(GetDisplayModeList)(This,EnumFormat,Flags,pNumModes,pDesc)	\
STDMETHOD(FindClosestMatchingMode)(This,pModeToMatch,pClosestMatch,pConcernedDevice)	\
STDMETHOD(WaitForVBlank)(This)	\
STDMETHOD(TakeOwnership)(This,pDevice,Exclusive)	\
STDMETHOD(ReleaseOwnership)(This)	\
STDMETHOD(GetGammaControlCapabilities)(This,pGammaCaps)	\
STDMETHOD(SetGammaControl)(This,pArray)	\
STDMETHOD(GetGammaControl)(This,pArray)	\
STDMETHOD(SetDisplaySurface)(This,pScanoutSurface)	\
STDMETHOD(GetDisplaySurfaceData)(This,pDestination)	\
STDMETHOD(GetFrameStatistics)(This,pStats)	\
STDMETHOD(GetDisplayModeList1)(This,EnumFormat,Flags,pNumModes,pDesc)	\
STDMETHOD(FindClosestMatchingMode1)(This,pModeToMatch,pClosestMatch,pConcernedDevice)	\
STDMETHOD(GetDisplaySurfaceData1)(This,pDestination)	\
STDMETHOD(DuplicateOutput)(This,pDevice,ppOutputDuplication)	\
STDMETHOD(SupportsOverlays)(This)	\
"
)

DXGI1_3.IDXGIOutput3 := {}
DXGI1_3.IDXGIOutput3.name := "IDXGIOutput3"
DXGI1_3.IDXGIOutput3.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(SetPrivateData)(This,Name,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,Name,pUnknown)	\
STDMETHOD(GetPrivateData)(This,Name,pDataSize,pData)	\
STDMETHOD(GetParent)(This,riid,ppParent)	\
STDMETHOD(GetDesc)(This,pDesc)	\
STDMETHOD(GetDisplayModeList)(This,EnumFormat,Flags,pNumModes,pDesc)	\
STDMETHOD(FindClosestMatchingMode)(This,pModeToMatch,pClosestMatch,pConcernedDevice)	\
STDMETHOD(WaitForVBlank)(This)	\
STDMETHOD(TakeOwnership)(This,pDevice,Exclusive)	\
STDMETHOD(ReleaseOwnership)(This)	\
STDMETHOD(GetGammaControlCapabilities)(This,pGammaCaps)	\
STDMETHOD(SetGammaControl)(This,pArray)	\
STDMETHOD(GetGammaControl)(This,pArray)	\
STDMETHOD(SetDisplaySurface)(This,pScanoutSurface)	\
STDMETHOD(GetDisplaySurfaceData)(This,pDestination)	\
STDMETHOD(GetFrameStatistics)(This,pStats)	\
STDMETHOD(GetDisplayModeList1)(This,EnumFormat,Flags,pNumModes,pDesc)	\
STDMETHOD(FindClosestMatchingMode1)(This,pModeToMatch,pClosestMatch,pConcernedDevice)	\
STDMETHOD(GetDisplaySurfaceData1)(This,pDestination)	\
STDMETHOD(DuplicateOutput)(This,pDevice,ppOutputDuplication)	\
STDMETHOD(SupportsOverlays)(This)	\
STDMETHOD(CheckOverlaySupport)(This,EnumFormat,pConcernedDevice,pFlags)	\
"
)

DXGI1_3.IDXGISwapChain2 := {}
DXGI1_3.IDXGISwapChain2.name := "IDXGISwapChain2"
DXGI1_3.IDXGISwapChain2.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(SetPrivateData)(This,Name,DataSize,pData)	\
STDMETHOD(SetPrivateDataInterface)(This,Name,pUnknown)	\
STDMETHOD(GetPrivateData)(This,Name,pDataSize,pData)	\
STDMETHOD(GetParent)(This,riid,ppParent)	\
STDMETHOD(GetDevice)(This,riid,ppDevice)	\
STDMETHOD(Present)(This,SyncInterval,Flags)	\
STDMETHOD(GetBuffer)(This,Buffer,riid,ppSurface)	\
STDMETHOD(SetFullscreenState)(This,Fullscreen,pTarget)	\
STDMETHOD(GetFullscreenState)(This,pFullscreen,ppTarget)	\
STDMETHOD(GetDesc)(This,pDesc)	\
STDMETHOD(ResizeBuffers)(This,BufferCount,Width,Height,NewFormat,SwapChainFlags)	\
STDMETHOD(ResizeTarget)(This,pNewTargetParameters)	\
STDMETHOD(GetContainingOutput)(This,ppOutput)	\
STDMETHOD(GetFrameStatistics)(This,pStats)	\
STDMETHOD(GetLastPresentCount)(This,pLastPresentCount)	\
STDMETHOD(GetDesc1)(This,pDesc)	\
STDMETHOD(GetFullscreenDesc)(This,pDesc)	\
STDMETHOD(GetHwnd)(This,pHwnd)	\
STDMETHOD(GetCoreWindow)(This,refiid,ppUnk)	\
STDMETHOD(Present1)(This,SyncInterval,PresentFlags,pPresentParameters)	\
STDMETHOD(IsTemporaryMonoSupported)(This)	\
STDMETHOD(GetRestrictToOutput)(This,ppRestrictToOutput)	\
STDMETHOD(SetBackgroundColor)(This,pColor)	\
STDMETHOD(GetBackgroundColor)(This,pColor)	\
STDMETHOD(SetRotation)(This,Rotation)	\
STDMETHOD(GetRotation)(This,pRotation)	\
STDMETHOD(SetSourceSize)(This,Width,Height)	\
STDMETHOD(GetSourceSize)(This,pWidth,pHeight)	\
STDMETHOD(SetMaximumFrameLatency)(This,MaxLatency)	\
STDMETHOD(GetMaximumFrameLatency)(This,pMaxLatency)	\
STDMETHOD(GetFrameLatencyWaitableObject)(This)	\
STDMETHOD(SetMatrixTransform)(This,pMatrix)	\
STDMETHOD(GetMatrixTransform)(This,pMatrix)	\
"
)

DXGI1_3.IDXGISwapChainMedia := {}
DXGI1_3.IDXGISwapChainMedia.name := "IDXGISwapChainMedia"
DXGI1_3.IDXGISwapChainMedia.def :=
( 
"
STDMETHOD(QueryInterface)(This,riid,ppvObject)	\
STDMETHOD(AddRef)(This)	\
STDMETHOD(Release)(This)	\
STDMETHOD(GetFrameStatisticsMedia)(This,pStats)	\
STDMETHOD(SetPresentDuration)(This,Duration)	\
STDMETHOD(CheckPresentDurationSupport)(This,DesiredPresentDuration,pClosestSmallerPresentDuration,pClosestLargerPresentDuration)	\
"
)



Global DXGI_MULTIPLANE_OVERLAY_YCbCr_FLAG_NOMINAL_RANGE := 0x1
Global DXGI_MULTIPLANE_OVERLAY_YCbCr_FLAG_BT709 := 0x2
Global DXGI_MULTIPLANE_OVERLAY_YCbCr_FLAG_xvYCC := 0x4
Global DXGI_FRAME_PRESENTATION_MODE_OVERLAY := 1
Global DXGI_FRAME_PRESENTATION_MODE_NONE := 2
Global DXGI_FRAME_PRESENTATION_MODE_COMPOSITION_FAILURE := 3
Global DXGI_OVERLAY_SUPPORT_FLAG_DIRECT := 0x1
Global DXGI_OVERLAY_SUPPORT_FLAG_SCALING := 0x2

DXGI1_3.err := {}

